### ISSUE TITLE
PhpMyAdmin User/Privileges Issue  - Video #2 & #6

### ISSUE THREAD

**Issue by thedigicraft** [thedigicraft/Atom.CMS#1]
If you are getting a connection error in **Video 6** it is from a step in **Video 2**.  You need to:

> 1. Open PhpMyAdmin
> 2. Click on Users (sometimes called Privileges)
> 3. Edit the user
> 4. Change the host from Any Host to Local or type "localhost" in the text field (no quotes)

**Comment by reepz** [comment]
still doesn't work, exactly the same error message. not sure what im doing wrong.

**Comment by Vusa360** [comment]
Just as an update. If you follow all these steps and it doesn't work. I believe this error can be caused by using capital letters in your username.
