### ISSUE TITLE
Part 55 - Creating a User Management Page

### ISSUE THREAD

**Issue by rew7ind** [thedigicraft/Atom.CMS#106]
Hello in the start of this video he fixed the page manager issue. But when i clicked at one page to edit it didnt load anything. The debbuger show me tha the information about this page is loaded.
![1](https://cloud.githubusercontent.com/assets/11510654/6677623/78f5ae14-cc3a-11e4-8025-36041d433afc.png)

**Comment by creptor** [comment]
Pelase be sure to add an error, if you don't know how just remplace the error reporting in your config( or setup) file with this: `error_reporting(-1)`

**Comment by rew7ind** [comment]
I did it..
the error is:

Warning: include(views/Array.php): failed to open stream: No such file or directory in /home/u297726054/public_html/admin/index.php on line 3 Warning: include(views/Array.php): failed to open stream: No such file or directory in /home/u297726054/public_html/admin/index.php on line 3 Warning: include(): Failed opening 'views/Array.php' for inclusion (include_path='.:/usr/lib/php') in /home/u297726054/public_html/admin/index.php on line 3

**Comment by rew7ind** [comment]
i fixed it. I have a wrong letter in the setup.php.
thank you creptor for the help.
