### ISSUE TITLE
My apache module won't boot up

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#107]
So I restarted the website and I'm like part 44. So far so good. Anyways, the reason I'm posting an issue is because my apache won't start. The other two will. I have a theory that it may be because my internet connection shows up as limited even though it works perfectly fine. I'm not sure as to why it does this. Any other connection doesn't do that, and all my other devices and Pc's can connect to it just fine. Not sure if anyone can help on this, but if you can please let me know. I'd hate to be trolled into not coding for the second time in a row :'(.... 

P.S: It's not because port 80 is being used. It'd show code red if it did. It just shows code yellow and fails to start.

**Comment by creptor** [comment]
Internet connection is not required for running appache. Error's with ports are often mistakes computer side, or i just said that to keep things simple. Just reboot your pc, run apache. If it doesn't work, please just change the port from 80 to wathever you desire, then to access your website just use:

`http://localhost:{port number}`

**Comment by Chriswilldo** [comment]
Alright so I solved it along with my internet connection. I had to refresh my windows 8 and re install xampp but it still worked. Had I known that all I had to do is rebuild my mysqli in order for my website to work again... But oh well. Least now I know
