### ISSUE TITLE
Working on quick install file.

### ISSUE THREAD

**Issue by JasonMate** [thedigicraft/Atom.CMS#111]
Hey Guys,

I have a version of atom.cms I've been working on for a little over a year and have managed to add some features to the core system (Alan has helped me out with several sections), mostly admin panel features. I included a quick install file, but it's still work in progress.

Anyway as an attempt to learn github I made a repository. I know there are lots of developers following the Atom.cms project  so I thought I would throw this out there if any one is interested.

https://github.com/JasonMate/AtomProject

**Comment by creptor** [comment]
So it will auto install the databse and all that stuff?
How nice contribution. I have tought on that but it seems for me kind of... overtaking things, but if he help you out then i guess there is no problem :smile: (due this is also free for all :P)

**Comment by JasonMate** [comment]
Thats not my intention at all. Its just my own development where Alan left.
I feel like I have learned more about PHP from Alan's videos than I have in
the past 2 years of college web development. ha

**Comment by creptor** [comment]
I had know only css and html since alan's videos so that's why i'm so grateful and help new joining people in the web for any starter ideas that peaple may get or give to this world.

PD: im not saying you're overtaking things, just kind of explaint to me why I have'nt done that to help the actual repository.(I whant them to seek the capabilities of the web, and be impress with what they have just learned) and you are doing just that. Nice work.

**Comment by creptor** [comment]
Also I recomend a thing i added for my web, wich is a custom web admin css editor wich helps me edit the page on my mobile when I see errors, and for new things web on creating new.... classes, but that's other factor :3

**Comment by creptor** [comment]
Also I was looking at your code (for the unlic :3) and I found you use repeated mysql queries, you could use mysqli_multi_query.

**Comment by JasonMate** [comment]
For sys.config.php ?

**Comment by JasonMate** [comment]
I tried installing this on a 1&1 account and having trouble getting the clean urls to work correctly. I guess I will try installing it on wamp or something to see if it works locally. I did almost all the work on a live server.

**Comment by creptor** [comment]
yea for the sys.config.php oyu can use multi_query, Wich should be faster do is in one query (and less memory should be needed,because of only one process)

**Comment by creptor** [comment]
I'm working on an auto install file for my web, it currently works, and when I finish I'll try it online and post it :3

**Comment by JasonMate** [comment]
Ah way cool, thanks creptor. Two heads is always better than one! The one I did has the queries set up like they do because the entire file and queries are based off the database export file you get off phpMyAdmin.

**Comment by creptor** [comment]
I have just ended my auto install script, please look at it and tell me what you think. https://github.com/creptor/atom.cms-With_auto_installer/tree/master

**Comment by JasonMate** [comment]
I can't find the script, what is folder and file name?

**Comment by creptor** [comment]
you're supposed to just go to web, and then it will redirect you to the install.... else it's the install folder.

**Comment by thedigicraft** [comment]
@JasonMate @creptor FYI I am going to take a look at both of these projects as soon as I get a free moment! I am excited to see what you guys have done and thank you both for your comments!!!

**Comment by JasonMate** [comment]
Hey Alan, after looking closely at your repository, I realized I uploaded some plugins that I shouldn't have so I took my repository down. I figured it would be better if I just fork the repository you have and work off that.
