### ISSUE TITLE
Database data example

### ISSUE THREAD

**Issue by creptor** [thedigicraft/Atom.CMS#113]
I really need the data from the database created in the series, because i lost mine. Please if you have finished the series it would be nice if you gave me a copy of it.

Here is how:
- go to php my admin
- click the table in where you're working the series
- click export, and continue.(with sql please)

And then upload the file here, thanks

**Comment by ninasmurffh** [comment]
I haven't completely completed the series, but i think i left at part 106(?), so i guess this is better than nothing.
Github doesn't let you upload anything else than image files so i downloaded it to dropbox:
https://www.dropbox.com/s/vus8sbnzzstrcui/database%20%281%29.sql?dl=0

**Comment by creptor** [comment]
thanks :smile:
