### ISSUE TITLE
Video 44

### ISSUE THREAD

**Issue by RosemaryRoss** [thedigicraft/Atom.CMS#119]
First, let me thank you for creating a great tutorial.  I have gotten stuck on video 44, in that the code that DID work, is no longer working.  The page would update, but not add a new page.  I watched #44 so many times I think I can recite it verbatium, however....I've "redone" the code so many times that I'm just beyond confused and I feel I've messed the code up so bad that I don't know where I'm at in the code.  Can anybody please show me the code that WORKS so I can move on.  (I've gone back and redone my entire learning site three times already, I just don't have it in me to do it again from scratch.)

Thanks for any help given.

Rosemary

**Comment by creptor** [comment]
please provide the code(like function or part) that you whant and the posible file it's located in.

Or post your code, and I'll help you fix it.

**Comment by RosemaryRoss** [comment]
Oh that would be great.  
The code is on my work computer, I’ll get it tomorrow.

 

R

**Comment by creptor** [comment]
allright, I'll be here tomorrow at 8pm:smile: EST -4:00

**Comment by RosemaryRoss** [comment]
Hopefully this isn't "Mission Impossible" for you.  I know I've screwed the code up so bad that this is the error message:
Parse error: syntax error, unexpected end of file in C:\wamp\www\Aptana\AtomCMS\admin\index.php on line 181   (181 being the last line in code).

The code used to work for "updating" the page.   Although it said it ADDED a new page, it did not in reality.  Tried very hard to find my mistake, and only created such a big mess that I'm totally confused, and really messed up the code.

 I did the programming in Aptana (which is pretty cool),   I think this is where the error is.  If not....I'll try again.
I think I'll have to copy this file and take it home so I have it available.

![screenshot 2015-04-21 08 27 21](https://cloud.githubusercontent.com/assets/12034536/7252247/3ab2e8a0-e801-11e4-96c7-06b886ec65c0.png)

Gosh, I hope you can help, and this isn't too much trouble for you.
R

**Comment by creptor** [comment]
you didn't close the else statement.... put a `}` right after the insert querry.

**Comment by RosemaryRoss** [comment]
THAT was it????
OMG….I have found tiny mistakes like that before, but this time I was starting to go crazy.  I’ll put that } in and hopefully that does the trick.

I’ll get back to you on that one, because it wasn’t adding a page…..SO, as soon as I put in the } I’ll try it out.


Thanks.

**Comment by RosemaryRoss** [comment]
Oops, can’t check at home.  I forgot to bring the database too.  Will check it out tomorrow.

Thanks for the help….I really DO appreciate it.


R

**Comment by RosemaryRoss** [comment]
Put the } in and the good news it that I can now see the form again.
The bad news.....the form still does not work.  Does not "add" a page, does not "update a page".  I hate to add three screen shots, but here is the code from my index page in the admin folder.
![screenshot 2015-04-22 08 30 51](https://cloud.githubusercontent.com/assets/12034536/7274406/6faaf86c-e8ca-11e4-9f28-f401b2727544.png)
![screenshot 2015-04-22 08 31 34](https://cloud.githubusercontent.com/assets/12034536/7274407/6faed446-e8ca-11e4-8e9e-b1fd005da650.png)
![screenshot 2015-04-22 08 32 05](https://cloud.githubusercontent.com/assets/12034536/7274408/6faf01fa-e8ca-11e4-9864-d755b5fd106b.png)

**Comment by creptor** [comment]
if you have any errors please post them. It's necesarry that you actually tell me what is not working, and how it's supossed to work, please.

**Comment by RosemaryRoss** [comment]
That is just it.  I don’t get an error message.  When you make an “update”, you get the message the update was made, but in reality it was not.  When you try to add a new page, the message is given new page added, but there is no new page.

**Comment by JasonMate** [comment]
The method attribute in your form tag looks like it has a space that
doesn't belong there, right after the =

**Comment by RosemaryRoss** [comment]
I sincerely wished that was the issue. Took out the space and the form still does not do the ACTION. It does not update, it does not add a page. Just refreshes. 

----- Original Message -----

**Comment by JasonMate** [comment]
It says "updated" but the pages are not going the database? Can you take a
screenshot of your pages table?

**Comment by RosemaryRoss** [comment]
Glad to know you didn't give up on me.
![screenshot 2015-04-23 13 50 54](https://cloud.githubusercontent.com/assets/12034536/7303610/e7a7339e-e9bf-11e4-9990-db464b87dc2a.png)

**Comment by JasonMate** [comment]
I'm pretty sure the problem is your INSERT query. It's hard to see in the
screenshot, but it looks like VALUES portion of that query is missing the
variables you created above.

Should look like this:

$q = "INSERT INTO pages (user, slug, title, label, header, body) VALUES
($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";

Let us pray that is the problem :)

**Comment by RosemaryRoss** [comment]
I know tiny little mistakes cause huge problems. And, the screenshot isn't so great. SO, here is the entire php block. I think the INSERT is as you have below (or I've gone batty looking at it so long). 

<?php 

if(isset($_POST['submitted']) == 1){ 

//need to create an "escape" to deal with apostropies and things that break code, ie Alan's page 
$title = mysqli_real_escape_string($dbc, $_POST['title']); 
$label = mysqli_real_escape_string($dbc, $_POST['label']); 
$header = mysqli_real_escape_string($dbc, $_POST['header']); 
$body = mysqli_real_escape_string($dbc, $_POST['body']); 


if(isset($_POST['id']) != ''){ 
$action = 'updated'; 

$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]"; 
}else{ 
$action = 'added'; 
$q = "INSERT INTO pages (user, slug, title, label, header, body) VALUES($_POST[user], '$_POST[slug]', 'title', 'label', 'header', 'body')"; 

$r = mysqli_query($dbc, $q); 

}if($r){ 

echo '<p>Page was '.$action.'!</p>'; 
}else { 
echo '<p>Page could not be '.$action.' because: '.mysqli_error($dbc); 
echo '<p>' .$q. '</p>'; 
} 
} 

?> 


----- Original Message -----

**Comment by JasonMate** [comment]
Replace this:
$q = "INSERT INTO pages (user, slug, title, label, header, body)
VALUES($_POST[user], '$_POST[slug]', 'title', 'label', 'header', 'body')";

With this:
$q = "INSERT INTO pages (user, slug, title, label, header, body)
VALUES($_POST[user], '$_POST[slug]', '$title', '$label', '$header',
'$body')";

**Comment by creptor** [comment]
You have your update query wrong. It appears you're ussing the `$_POST` data but in the update query you use  the `$_GET`, please replace it. Example:

```
$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_POST[id]";
```

**Comment by RosemaryRoss** [comment]
JasonMate - I used your replacement...unfortunately, it didn't work.  The form just sits there, no update, no new page either.

Creptor - I tried your suggestion and changed the code from $_GET[id]"; to $_POST[id]"; and that didn't work.  I used the POST with both mine and CodeMate's suggested change and still, the form does nothing.  
I'm feeling like a hopeless cause  :-(    And, I can't move forward with the tutorials until this works.

**Comment by JasonMate** [comment]
Hey Rose,
  I'll try and help you resolve it after I get off work this afternoon.
Also I would look and study the queries Alan is using for that page here:
https://github.com/thedigicraft/Atom.CMS/blob/master/admin/config/queries.php

**Comment by RosemaryRoss** [comment]
Thanks, I do appreciate your help. Don't knock yourself out though, as I'm going to be out of town this weekend, and I can't work on it until Monday. BUT, I will watch the video this afternoon, and go back and review the tutorials (again)....just maybe some lightning bolt will happen!! 
R 

----- Original Message -----

**Comment by RosemaryRoss** [comment]
I think you are right. I DO have a problem with /config/queries.php 
I need to go back and review the videos to find where I missed creating this file. 
My setup makes reference to it, but I don't have that file. 
Back to the videos. 

----- Original Message -----

**Comment by creptor** [comment]
consider posting the hole actual code in here. It would be mor helpfull to use http://pastebin.com/.

I'll need the file where the form is,and where the query is. (considerating that everything else works perfectly and the database is correctly input by the queries)

**Comment by RosemaryRoss** [comment]
Thank you...I took out ALL my code for the form and started over.  When I get to that video 44, and I still have issues.....I'll implore your help again....I can't find my mistake so I'm just trying it all over again.

**Comment by RosemaryRoss** [comment]
Totally redid the coding.  Got to video 44.  I can ADD a page, but I cannot UPDATE a page.  the admin page just keeps adding a new page instead of updating the content of a page.  I can't make alterations to an already created page.

**Comment by RosemaryRoss** [comment]
Okay.  I've spent the last 3 days completely redoing the code, starting from scratch.  Got to video 44 and have the same issues.  Looking over the other questions posted...it appears there is an ISSUE with video 44 and the code therein.  

One thing I noted (after watching the video 10 times, was that Digicraft said $ when in reality he meant ?, so there may be another error somewhere in there that I, as a student, cannot pick up on.

Here is the error:
Page could not be added because:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[id]' at line 1

UPDATE pages SET user = 2, slug = 'about-us', title = 'About Us 5', label = 'About', header = 'About AtomCMS', body = '

Same error everyone else got.    (they probably didn't redo the code 50+ times though)

My index.php code is as follows:

<?php
#START THE SESSION
session_start();
// session is an array and starts the session

if (!isset($_SESSION['username'])) {// this is what checks if a person is logged in.  username is the key.
	// IF not logged in, then header function sends user back to login page.
	header('Location: login.php');
}
?>

<?php
	include ('config/setup.php');
?>  
	

<!DOCTYPE html>
<html>
	
	
	<head>
			<meta charset="utf-8">
	    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
			<meta name="viewport" content="width=device-width, initial-scale=1">
		
			<title><?php echo $page['title'] . ' | ' . $site_title; ?></title>
			<?php
				include ('config/css.php');
			?>	
			
			<?php
				include ('config/js.php');
			?>	
			
	</head>
	
	
	<body>
		
		<div id="wrap">
			<?php
			include (D_TEMPLATE . '/navigation.php');
			#Main navigation
 ?>  
			
			<h1>Admin Dashboard</h1>
						
		
			<div class="row">
				
				<div class="col-md-3">
					<?php
					     # Changing this to GET did nothing.  No update, no error, no page added.  Does nothing.
						if(isset($_POST['submitted']) == 1 ){
							
							$title = mysqli_real_escape_string($dbc, $_POST['title']);  // real_escape_string is to handle apostrophies in the text.
							$label = mysqli_real_escape_string($dbc, $_POST['label']);
							$header = mysqli_real_escape_string($dbc, $_POST['header']);
							$body = mysqli_real_escape_string($dbc, $_POST['body']);
							
					# Must keep at $_GET as post does not work
						if(isset($_GET['id']) != '') {   
							$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET [id]";
												
						}else{
							$q = "INSERT INTO pages (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";  // the escaped version
					    }
						
						$r = mysqli_query($dbc, $q);
						
						// check to see if r has a value (debugging)
						if($r){
							
							$message = '<p>Page was added!';
						} else {
							
							$message = '<p>Page could not be added because:' .mysqli_error($dbc);
							$message .= '<p>' .$q. '</p>';
						}
					}
					
					?>
					
					<div class="list-group">
						
						<a class="list-group-item" href="index.php">
								<h4 class="list-group-item-heading"><i class="fa fa-plus"></i>  New Page</h4>  
								
						</a>
					
					<?php  
						$q = "SELECT * FROM pages ORDER BY title ASC";
						$r = mysqli_query($dbc, $q);
						
						while($page_list = mysqli_fetch_assoc($r)){ 
							
							$blurb = substr(strip_tags($page_list['body']), 0, 60);
							?>
							<a class="list-group-item" href="index.php?id=<?php echo $page_list['id'] ?>">
								<h4 class="list-group-item-heading"><?php echo $page_list['title']; ?></h4>
								<p class="list-group-item-text"><?php echo $blurb; ?></p>
							</a>
							
							
						<?php }	?>
						
						</div>
				</div> 
				
				
				
				<div class="col-md-9">
					
					<?php
						if(isset($message)){echo $message; } ?>
						
					<?php
					
						if(isset($_GET['id'])){
							
							$q = "SELECT * FROM pages WHERE id = $_GET[id]";
							$r = mysqli_query($dbc, $q);
							
							$opened = mysqli_fetch_assoc($r);
						}	
					
					?>
	
					
						<form action="index.php?id=<?php $opened; ?>"  role="form" method="post">
							
							<div class="form-group">
								<label for="title">Title</label>
								<input class ="form-control" type="text" name="title" id="title" value="<?php echo $opened['title']; ?>" placeholder="Title" />			
							</div>
							
							<div class="form-group">
								<label for="user">User</label>
								<select class ="form-control" name="user" id="user"> 
									<option value="0">No user</</option>  
									
									<?php
										$q = "SELECT id FROM users ORDER BY first ASC";
										$r = mysqli_query($dbc, $q);
										
										while($user_list = mysqli_fetch_assoc($r)){ 
											
											$user_data = data_user($dbc, $user_list['id']);
											?>
											
										<option value="<?php echo $user_data['id']; ?>" 
											<?php 
											if(isset($_GET['id'])){
												
												if($user_data['id'] == $opened['user']) {echo 'selected'; }
											}else{
												if($user_data['id'] == $user['id']) {echo 'selected'; }  //pulls the person who is logged in.
											}
											 ?>><?php echo $user_data['fullname']; ?></option>	
																	
										<?php } ?>
									
								</select>			
							</div>
							
							
							<div class="form-group">
								<label for="slug">Slug</label>
								<input class ="form-control" type="text" name="slug" id="slug" value="<?php echo $opened['slug']; ?>"placeholder="slug" />			
							</div>
							
							<div class="form-group">
								<label for="label">Label</label>
								<input class ="form-control" type="text" name="label" id="label" value="<?php echo $opened['label']; ?>"placeholder="label" />			
							</div>
							
							<div class="form-group">
								<label for="header">Header</label>
								<input class ="form-control" type="text" name="header" id="header" value="<?php echo $opened['header']; ?>"placeholder="Header" />			
							</div>
							
							<div class="form-group">
								<label for="body">Body</label>
								<textarea class ="form-control editor"  name="body" id="body" row="8" placeholder="body"><?php echo $opened['body']; ?></textarea> 		
							</div>
							
							<button type="submit" class="btn btn-default">Save</button>
							<input type="hidden" name="submitted" value="1">
							<input type="hidden" name="id" value="<?php echo $opened['id']; ?>">
							
						</form>
  						
				</div>
				
				
			</div>
			
			
			<?php
				include (D_TEMPLATE . '/footer.php');
 			?>
	
	<?php
		if ($debug == 1) {
			include ('widgets/debug.php');
		} #debug must be turned on in the database
 	?>
	
	 	
	</body>
</html>

I really do not want to give up learning, but I've hit a brick wall.  I seriously believe there is an issue in that particular video (or so many people would not have issue with it.)

**Comment by JasonMate** [comment]
Hey Rose,

I am chained to the comp for a couple hours so I can help if you want. :)


In your form tag I see your trying to echo out the array, It just needs
 $opened['id']

<form action="index.php?id=<?php echo $opened['id']; ?>" method="post"
role="form">


Also you may need to change this little bit of code here:

# Must keep at $_GET as post does not work
  if(isset($_GET['id']) != '') {


Its supposed to be:

if(isset($_POST['id']) != '') {


Regards,

Jason M

**Comment by JasonMate** [comment]
I don't know if this matters, but you can remove the space between $_GET
and [id] in your update query.

 WHERE id = $_GET[id]

**Comment by RosemaryRoss** [comment]
I’m SO sorry the code is on my work computer (I’m trying to learn php for our web site) and I don’t have it here at home.
I will most certainly try a few of the suggestions you listed, but I know for a fact that the > if(isset($_POST['id']) != '') {
does not work…that is why I made a note to myself to quit trying it.

 

I hope one of your suggestions work when I try it tomorrow morning.  I’m ready to throw in the towel.

R

(BTW ~~ from the id count…I can tell today alone I “added” 20 pages and not one update)

**Comment by RosemaryRoss** [comment]
I wish there was a better way to communicate. This is getting lengthy. I made the first change suggested (the form action=) 
Here is the error message: 


Page could not be added because:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[id]' at line 1 

UPDATE pages SET user = 2, slug = 'about-us', title = 'About Us ', label = 'About', header = 'About AtomCMS', body = ' 

Even though changing $_GET to $_POST has not worked in the past...I'll give it a try in conjunction with the above change. 

R 
----- Original Message -----

**Comment by RosemaryRoss** [comment]
There is an error in the code that is supposed to update. Prior to adding that code I COULD add a new page. After adding that update code I can no longer add a page either. SO, the code for making the update is obviously wrong. I am trying to learn how to code, so I can't figure out the error. BUT, through deductive reasoning, I know the error is in the update code. 
I'm sad you could not spot the problem. 
R 



----- Original Message -----

**Comment by creptor** [comment]
I have just found it....
in the query here:
```$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET [id]";```
You placed a space in between the `$_GET` and the `[id]` so the php doesn't recognizes the variable... please fix it.(`$_GET[id]`)

**Comment by RosemaryRoss** [comment]
Shucks....I wish that was it.  JasonMate mentioned that fix yesterday.  I corrected it this morning....and it still didn't work.  The problem is definitely in the UPDATE though, because before I put that in, it added a page just fine.  Now....it doesn't update OR add a new page.

**Comment by JasonMate** [comment]
Hey Rose,

Ok here are the problems I see with the code.

1. The form tag.

<form action="index.php?id=<?php $opened; ?>"  role="form" method="post">


You are appending an array to the id. It needs to be like this:

<form action="index.php?id=<?php echo $opened[id]; ?>" role="form"
method="post">


2. The form uses the the POST method but you are checking for a GET. I
think the reason its not working is because the id would be coming in
empty every time and just post rather than update.


   # Must keep at $_GET as post does not work
   if(isset($_GET['id']) != '') {

This needs to be post because the form submits the $opened['id'] in a
hidden field at the bottom of your form.


3. Here's the update query you have:

$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]',
title = '$title', label = '$label', header = '$header', body = '$body'
WHERE id = $_GET [id]";

Everything looks good except the very last part. You need to remove
the space between $_GET and [id]

Please fix all these problems first and test it. If there is still
problems we can drill down further and take a closer look, but the
obvious problems need to be fixed first. Also it will be a lot easier
to look at your code if you use http://pastebin.com/ and share all the
files involved.

I know bugged code can be extremely frustrating. Just keep at it like
the rest of us and eventually you figure it out. :)


Jason M

**Comment by RosemaryRoss** [comment]
Made a little progress with your suggestions below. I can now UPDATE a page, but not ADD a new page. 
I joined paste.bin (not sure I pasted properly and all that is needed). 
Does what I pasted help solve the mystery?? Need more files?? 
And, again, THANKS. 
R 


----- Original Message -----

**Comment by JasonMate** [comment]
Hey Rose,

I can help after work. Can you provide some links to the pastes you put up?
Please don't paste your connection file.

best regards,

Jason M

**Comment by RosemaryRoss** [comment]
What do you need as links?? (sorry, ...new at this) 
I posted 5 files. I'm not sure what other files are needed. 


----- Original Message -----

**Comment by JasonMate** [comment]
If you posted the files on pastebin.com then I will need the links to each
file you posted.

Like this:
http://pastebin.com/ubgGNsED

**Comment by RosemaryRoss** [comment]
Oh. 
http://pastebin.com/pBvW9JB8 

http://pastebin.com/A663ZBQy 

http://pastebin.com/HqSPpPcp 

http://pastebin.com/sKbMnf6U 

http://pastebin.com/qny3ZAAR 

I wondered how this worked. 



----- Original Message -----

**Comment by JasonMate** [comment]
Hey Rose,

I just looked over your code, and I can't see any problems with the INSERT
query you have.
The only thing I found is on index.php line 139:
<option value="0">No user</</option>  
It looks like you closed the option tag twice. I don't think that is the
problem though...

If it updates, we know its getting an id. When you post I think the id
comes in empty, and the database will auto-increment the id for the new
post.

Is there an error when you try to post?

Do you have anything in queries.php yet?

**Comment by RosemaryRoss** [comment]
No, I don’t have anything in queries.php yet.

The code does update.  But won’t add a new page.

You guys are great to be able to look over code and spot glitches.

**Comment by RosemaryRoss** [comment]
I’ll copy the error message and show you tomorrow.

**Comment by JasonMate** [comment]
Do you have id set to auto increment in the pages table?

**Comment by RosemaryRoss** [comment]
Yes, id is set to auto increment. 

This is the error message when trying to ADD a page: 


Page could not be added because:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 

UPDATE pages SET user = 4, slug = 'New Page Monday', title = 'New Page', label = 'New Page', header = 'New Page', body = ' 

trying to add a page ' WHERE id = 

I'm user 4 in the user table. 

Not knowing enough about code, and trying to learn, is what makes this difficult. I can't find the mistake because I don't totally understand all the code. 

----- Original Message -----

**Comment by RosemaryRoss** [comment]
If I switch the $q = "INSERT INTO pages with $q = "UPDATE pages (just reverse their position), I can then ADD a page, but you lose the ability to UPDATE a page. 
At this point, I think I have my code (or did before I switched them) exactly like the video. 




----- Original Message -----

**Comment by JasonMate** [comment]
Hey Rose,

That pretty much means that both queries are good. There is some type of
logical error that I can't spot unless I go watch all the videos again. I
know a lot of this code will be moved to queries.php eventually in the
series.

I'm just shooting in the dark, but a guy in the comments on video 44 said
he was having similar problems and this worked for him:

He replaced:
if(isset($_POST['id']) != '') {

With:
if(isset($_POST['id']) != 'NULL') {

It wouldn't hurt to try it and see.

Sorry couldn't help more :(

Jason M

**Comment by RosemaryRoss** [comment]
I’m going to give that a try, because it seems to me (you are right) that both queries work….just not together.  So, my plan is first to try the recommended fix below.  IF that doesn’t work (and it may not…who knows), THEN I’m going to put it back to a page will UPDATE, and I will just add a page manually through the database so I can move forward.  Otherwise, I’m stuck on 44 with no further progress.

I sincerely DO appreciate your efforts.  Learning this stuff via videos is SOoooooo freaking hard.

Thanks.


R

**Comment by creptor** [comment]
maybe you could do an if exist in your query, beacause the one updating doesn't work and the one creating it does, so you make sure that it works, and it works perfectly :smile:. I'll try to write you an example.... (It would be for now so maybe later you could fix this way, and still use the admin section from your page :+1:)

**Comment by creptor** [comment]
o and you should always wrap the values (like: `user=$asd`) inside apostrophe to avoid missunderstanding of the values you input...... like for the email :P

Example:
`user='$_POST[user]'`

**Comment by RosemaryRoss** [comment]
Thanks. I put '$_POST[user]' in. didn't make a difference though. So I took it back out as the video said user was numeric value. I'll try the next video and just manually ADD a page through the database....until I figure this out. Great mystery. 


----- Original Message -----

**Comment by creptor** [comment]
have you tried to input what you get (echoing the $q) into the phpmyadmin with sql method.... this gives and detailed error. Or at least i can understand them.(sometime I do this to find query errors)

**Comment by RosemaryRoss** [comment]
Oh, I hate to say this.  I’m too much of a newbie to understand what you just suggested.

I’ve decided to move forward with the videos, and now I have a bigger problem.  I did everything through video 48, and now the front end doesn’t show up at all.  Nothing.  Nada. No page.

Back to the drawing board.


Rosemary

**Comment by creptor** [comment]
if you wish to move on from this thread just leave it or close it... If you need more help in something diferent please create a new issue.(this one is kind of long)

**Comment by RosemaryRoss** [comment]
Good idea.  I thank you and JasonMate for your help.  I appreciate it much.  :-)   +1:

**Comment by gautam03** [comment]
Hey i just removed the isset function. like this:
if(($_POST['id'])!=='') and now both the queries are working fine. But i don't know how. Please someone tell me how this is working? or is it necessary to use isset for any reason?

**Comment by RosemaryRoss** [comment]
gautam03,  count your blessings then.  Making that change didn't work for me.  I just scraped AtomCMS and started AtomCMS2.  I discovered I was using the OLD tutorials and now am using the current ones.  I still am making my share of stupid mistakes, but I'm trying to learn this .php "stuff".
