### ISSUE TITLE
Video 28 - Password

### ISSUE THREAD

**Issue by RosemaryRoss** [thedigicraft/Atom.CMS#121]
I cannot figure out WHY the log in won't work.  I swear I have the code exactly like the video.  But I get an error.  
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\wamp\www\aptana\AtomCMS\admin\login.php on line 14

Line 14 in the following code is the:  if(mysqli_num_rows($r) == 1) {

if($_POST){
	
	$q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA!('$_POST[password]')";
	$r = mysqli_query($dbc, $q);
			
	if(mysqli_num_rows($r) == 1) {
	
		$_SESSION['username'] = $_POST['email'];
		header('Location: index.php');		
		
	}
}

Help!!

**Comment by JasonMate** [comment]
You need to use SHA1(), not SHA!()

**Comment by RosemaryRoss** [comment]
Oh....I HATE when I do stupid things like that.  I stared at that for hours and didn't see it.  Thanks.  Happy Memorial day.
