### ISSUE TITLE
Part-30 dropdown menu

### ISSUE THREAD

**Issue by gautam03** [thedigicraft/Atom.CMS#127]
Hi
Thanks for the amazing tutorials. These are really helping.
I have an issue with the the dropdown menu. I checked my code many times but the problem i'm facing is when i'm clicking on the menu button no action is taking place, it shows no menu. I directly copied the code from bootstrap also . but still i'm facing the same problem. What should i do now.!

**Comment by creptor** [comment]
well that depends... mostly it's because you don't have all bootstrap files correctly added to your page....

For drop-down menus you need the javascript and the css from bootstrap.

---------
Check that you have this line of code:
```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
```

**Comment by gautam03** [comment]
Thanks for the help. actually i downloaded the files at the start. and I didn't the change the folder location in href correctly.

**Comment by creptor** [comment]
Nice. Just remember to close the issue.

-- It will get worse, I once placed a capital letter in some code and took me a day to find it T_T
