### ISSUE TITLE
part 76: file not re naming properly

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#133]
Ok so I'm having some issues here with my dropzone. Keep in mind that I tried using the new one because I didn't think it would make a difference. Everything was working alright until I spotted the issues with it. For one, I can't upload anything bigger than 2MB with my dropzone. I tried going into dropzone.js to try to change that, but unfortunately I am not smart enough to do it right. Also, when I tried doing part 76 with the new coding, it wouldn't properly name the same image. It would show the new name, but it would be converted into a text file. I'm not sure what to do at this point. I tried using the old dropzone used in this tutorial, but the spritemap.png won't work and I can no longer grab it from the dropzone site anymore. Any ideas? I really want to use the new one, but if push comes to shove, I don't need to.

**Comment by creptor** [comment]
That would be more complicated than just changing the code itself... the uploading process is defined by the server, php, and the script (so you won't find these problems), so you'll need to do some research first.

-- I don't recomend changing the default settings, because it may cause unwanted results.

**Comment by Chriswilldo** [comment]
Alright. I guess I will just use the old dropzone then.

**Comment by JasonMate** [comment]
You can bypass the php.ini by adding this code to your .htaccess file.

php_value upload_max_filesize 20M
php_value post_max_size 20M
php_value max_execution_time 1000
php_value max_input_time 1000

This fixed the problem for me.

**Comment by JasonMate** [comment]
I tested that on my local server (wamp) and it worked, but I just tested it
on my live server and got a server misconfiguration error. Boooo.

This code works, use this instead:

<IfModule mod_php5.c>
   php_value upload_max_filesize 20M
   php_value post_max_size 20M
</IfModule>

**Comment by Chriswilldo** [comment]
Thanks, that did help with the maximum upload size. I still want to keep the old dropzone just in case. It's not the much of a difference overall anyways, and I don't want to tamper with coding just yet.
