### ISSUE TITLE
Part 91: $list undefined?

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#137]
![error](https://cloud.githubusercontent.com/assets/8390023/8344611/7e063032-1aa9-11e5-9991-93b7f14aa321.PNG)

For some reason every since I edited my list-sort.php I've been getting this error. Because of it, I can't move on. I tried looking in my coding to see if anything is wrong, but as far as I can see, nothing is. PLZ HELP!!! *urgent.

When I comment out the edits it seems to work fine. I think?
![confusion](https://cloud.githubusercontent.com/assets/8390023/8344684/65f09e78-1aaa-11e5-9634-8b9cfcdbf421.JPG)

**Comment by creptor** [comment]
aparently your data is not beeing sent over to the php script.... search on you other code if you're using `$_POST` or `$_GET` they're different. (and that you-re sending list values... due to the `$_GET['list']`)

**Comment by Chriswilldo** [comment]
Hahaha I'm stupid. I was missing a _ to connect the li to php echo $list id. I guess I never noticed it because I wasn't paying enough attention to it. Thanks.
