### ISSUE TITLE
Avatar Refresh Video 79

### ISSUE THREAD

**Issue by Dragotic** [thedigicraft/Atom.CMS#139]
Hello guys,

lets go right into it! My avatar doesn;t refresh when a new one is uploaded. Here is the code:

From users.php
```php
<?php if(isset($opened['id'])) { ?>
	<script type="text/javascript">

		$(document).ready(function{

			Dropzone.autoDiscover = false;

			var myDropzone = new Dropzone("#avatar-dropzone");

			myDropzone.on("complete", function(file) {

				$("#avatar").load("ajax/avatar.php?id=<?php echo $opened['id']; ?>");

			});
		});

	</script>
<?php } ?>
```

From avatar.php
```php
<?php 

include('../../config/connection.php');

$id = $_GET['id'];

$q = "SELECT avatar FROM users WHERE id = $id";
$r = mysqli_query($dbc, $q);

$data = mysqli_fetch_assoc($r);

?>

<img src="../uploads/<?php echo $data['avatar']; ?>">
```

**Comment by creptor** [comment]
For best results with load place the sentence just after the end of the php, like this -> `?><img src="../uploads/<?php echo $data['avatar']; ?>">`

Then you have to make sure the path to the image is right. (for the script you give, the image is at `[root of file showing the image]/uploads/image`)

Finally search inside of your database that the images names are stored with there extensions... like .jpg , .png , etc.

**Comment by Dragotic** [comment]
Unfortunately the first option didn't work. As for the other one, both the path and the extensions are correct. I just said that it doesn't refresh the avatar by itself, if i do refresh the page by myself the new picture is loaded.

**Comment by creptor** [comment]
You can try looking at the code first, and then compare it to when you upload a image, to look for errors or mistakes. If you don't know or be sure of this just post it here. :smile:

**Comment by JasonMate** [comment]
You could try on "success like this.

        $(document).ready(function{

            Dropzone.autoDiscover = false;

            var myDropzone = new Dropzone("#avatar-dropzone");

            myDropzone.on("success", function(file) {

                $("#avatar").load("ajax/avatar.php?id=<?php echo
$opened['id']; ?>");

            });
        });

**Comment by Dragotic** [comment]
I'm so stupid...if you look at the first function inside <script></script> from users.php i forgot to put () after the function! 

really stupid of me :/ Anyway, thank you guys :+1:

**Comment by JasonMate** [comment]
Ha nice catch! :P
