### ISSUE TITLE
Open home page always when domain name is on the address bar - Video 51

### ISSUE THREAD

**Issue by ricmach** [thedigicraft/Atom.CMS#147]
```html+php
<?php
	/*Setup File:
	
	
	
	
	
	*/
	
	error_reporting(0);
	
	#Database Conection here
	
	include('config/connection.php');
	
	#Functions:
	
	include ('functions/sandbox.php');
	
	include ('functions/data.php');
	
	include ('functions/template.php');
	
	if(!isset($path['call_parts'][0]) || $path['call_parts'][0] == ''){
	
										//$path['call_parts'][0] = 'home';
										
										header('Location: home');
										
										}
										
	#Page Settings:
	
	$path = get_path();
	
	$debug = data_status($dbc, 'debug-status');
	
	#Page Setup:
	
	$page = data_page($dbc, $path['call_parts'][0]);
												
	$site_title = 'Plataforma de E-Commerce';
	
	$page_title = 'Home';
	
?>
```

**Comment by ricmach** [comment]
I'm Portuguese and I'm trying to change the Firefox language settings but without success.

I post below the error but I understand it's dificult for you to understand because it's Portuguese but I'm going to continuing trying to change the language of Firefox.

![error_message](https://cloud.githubusercontent.com/assets/15876900/11196386/9f300004-8cae-11e5-8273-11420dc14c16.jpg)

**Comment by thedigicraft** [comment]
Is your site hosted on your local computer or is it hosted somewhere we can look at it?

**Comment by ricmach** [comment]
I am working in my computerbin a localhost.

**Comment by creptor** [comment]
ho, I see the error.....
the if(page exists) must be before the `$path = get_path();` or else it would never be defined :smile:.

**Comment by creptor** [comment]
just remember that every variable must or should be after the functions are defined :3

**Comment by thedigicraft** [comment]
@creptor good catch!
