### ISSUE TITLE
Part 79 - Dynamically Change Preview Image on Upload

### ISSUE THREAD

**Issue by AnderSco01** [thedigicraft/Atom.CMS#152]
Hello,

I am having an issue with this one. I have done everything said but whenever I try to upload an image it never updates immediately. The jQuery, displaying avatar, DropZone form and avatar file code is attached. By the way, the file names and id variables are my own. Any help would be much appreciated thank you.

[dropzone_fault.txt](https://github.com/thedigicraft/Atom.CMS/files/75282/dropzone_fault.txt)

**Comment by creptor** [comment]
Hi.. I belive your code is fine, what you should do is verify that an image is sent from the actual ajax script... something like this: `<img src="uploaded/<?php echo $user_opened['avatar']; ?>"/>` so that it loads the image again :P if this is not the error, please post the ajax script here :3

**Comment by AnderSco01** [comment]
Thanks creptor, I moved the jQuery script to the bottom of the page, seems it did not detect it, all ok now, thank you very much!
