### ISSUE TITLE
Admin interface - Title bar error - Only shows first letter of each nav button

### ISSUE THREAD

**Issue by dbashby** [thedigicraft/Atom.CMS#164]
Upon completion of the project, video 112, I noticed that the title bar only displays the first letter of any of the hard coded navigation buttons but also the site title does not carry over.

In the form on the Settings form if I change the title, it saves to the database but in the title bar it is still taking the title from the hard coded site title on setup.php on the admin side.

I noticed in the final video that Alan had the same issue as far as the navigation bar only displaying the first letter of each button.

Has anyone else experienced this? If you did how did you fix one or both issues?

Thanks for any help.

![screenshot1](https://cloud.githubusercontent.com/assets/6895380/13234964/5c5d42ee-d9b3-11e5-9a39-c94824739303.png)
![screenshot2](https://cloud.githubusercontent.com/assets/6895380/13234967/5faec170-d9b3-11e5-9162-34a80c803ce1.png)
![screenshot3](https://cloud.githubusercontent.com/assets/6895380/13235065/e22b2210-d9b3-11e5-884e-e2346364b952.png)

**Comment by creptor** [comment]
you should really post code here.
Place the `setup.php` and the `index.php` code, use http://pastebin.com/ .

**Comment by dbashby** [comment]
Pastebin url - http://pastebin.com/raw/RcnknBmM

**Comment by creptor** [comment]
You have the site title as an static variable... in line 23 in `setup.php`. (`$site_title = "My Site";`)
Change it to `$site_title = data_setting_value($dbcon, site-title');` and it should be fixed.

**Comment by dbashby** [comment]
Thanks for that,
`$site_title = data_setting_value($dbcon, 'site-title');`
Resolved the one issue but the issue regarding the navigation only displaying the 1st letter in the hard coded navigation bar is still baffling.  As the screenshots above the page title is only showing the first letter and it is in lower case despite the Navigation as below. 

Thanks

`<nav class="navbar navbar-default" role="navigation">
    
        <ul class="nav navbar-nav">
            
            <li><a href="?page=dashboard">Dashboard</a></li>
            <li><a href="?page=pages">Pages</a></li>
            <li><a href="?page=users">Users</a></li>
            <li><a href="?page=navigation">Navigation</a></li>
            <li><a href="?page=settings">Settings</a></li>
            
        
        </ul>
        
        <div class="pull-right">
        
            <ul class="nav navbar-nav">
                        
                <li>
                    <?php if($debug == 1){ ?>
                        <button type="button" id="btn-debug" class="btn btn-info navbar-btn"><i class="fa fa-bug"></i></button>
                    <?php } ?>
                </li>
                
                <li class="dropdown">
                	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $user['fullname']; ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    	<li><a href="logout.php">Logout</a></li>
                    </ul>
                </li>
                
                
          
            </ul>
       
   		</div>
    
</nav>`

**Comment by creptor** [comment]
To help you with that I need the `header.php` file, please.

**Comment by dbashby** [comment]
header.php

`<?php

	# Start the session
	session_start();
	
	if(!isset($_SESSION['username'])){
		
		header('Location: login.php');
		
	}

?>

<?php 
	//require('php/connection/conx.php'); 
	require('config/setup.php');
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?php echo $page['title'] . ' | ' . $site_title; ?></title>
<meta name=viewport content="width=device-width,initial-scale=1.0">

<?php 
	require('config/css.php'); 
	require('config/js.php');
?>
</head>

<body>

<div class="wrap">

	<?php require(D_TEMPLATE . '/navigation.php'); ?> 

Thanks for your help Creptor`

**Comment by dbashby** [comment]
After looking at the code again I see the lower case letter but still unsure why only the first letter is showing

**Comment by creptor** [comment]
that code looks not complete, but you can change the `<?php echo $page['title'] . ' | ' . $site_title; ?>``with `<title><?php echo $page. ' | ' . $site_title; ?></title>`

**Comment by dbashby** [comment]
I am starting to get the feeling that I have missed out on 1 or more videos.  Thanks for your help with all of the above though.
