### ISSUE TITLE
Part 57 - User Data not displaying & Active states 

### ISSUE THREAD

**Issue by dbashby** [thedigicraft/Atom.CMS#170]
I have reached 57 but again the same issue has come up as the last time I came to this part of the project.

At the start of 57 Alan cuts the following from setup.php

`if(isset($_GET['id'])){ $opened = data_page($dbc, $_GET['id']); }`

and pastes it at the bottom of the pages and users switch statement.  Once I follow those directions I lose the active state on both my pages.php but also users.php

At 7:50 in the video Alan clearly shows he has the active state running

My pages segment of the switch statement is

`case 'pages':
		
				if(isset($_POST['submitted']) == 1){
		
					$title = mysqli_real_escape_string($dbc, $_POST['title']);
					$label = mysqli_real_escape_string($dbc, $_POST['label']);
					$header = mysqli_real_escape_string($dbc, $_POST['header']);
					$body = mysqli_real_escape_string($dbc, $_POST['body']);
					
					if(isset($_POST['id']) != 'null'){
						$action = 'updated!';
						$q = "UPDATE posts SET 
							user = $_POST[user], 
							slug = '$_POST[slug]', 
							title = '$title', 
							label = '$label', 
							header = '$header', 
							body = '$body' WHERE id = $_GET[id]";
						
					} else {
						$action = 'added!';
						$q = "INSERT INTO posts (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
						
					}
					
					
					$r = mysqli_query($dbc, $q);
					
					#Debug Query
					if($r){
						
						$message = '<p>Page was ' . $action . '</p>';
						
					} else {
					
						$message = '<p>Page could not be ' . $action . ' because: ' . mysqli_error($dbc);
						$message .= '<p>' . $q . '</p>';
						
					}
					
				}
				
				if(isset($_GET['id'])){	$opened = data_page($dbc, $_GET['id']); }
		
		break;`

My users segment of the switch is

`case 'users':
		
				if(isset($_POST['submitted']) == 1){
		
					$first = mysqli_real_escape_string($dbc, $_POST['firstname']);
					$last = mysqli_real_escape_string($dbc, $_POST['lastname']);
					
					//May need to check update query firstname and lastname
					if(isset($_POST['id']) != 'null'){
						$action = 'updated!';
						$q = "UPDATE users SET 
							firstname = '$first', 
							lastname = '$last', 
							password = '$_POST[password]', 
							status = $_POST[status]
							WHERE id = $_GET[id]";
						
					} else {
						$action = 'added!';
						$q = "INSERT INTO users (firstname, lastname, password, status) VALUES ('$first', '$last', '$_POST[password]', '$_POST[status]')";
						
					}
					
					
					$r = mysqli_query($dbc, $q);
					
					#Debug Query
					if($r){
						
						$message = '<p>User was ' . $action . '</p>';
						
					} else {
					
						$message = '<p>User could not be ' . $action . ' because: ' . mysqli_error($dbc);
						$message .= '<p>' . $q . '</p>';
						
					}
					
				}
				
				if(isset($_GET['id'])){	$opened = data_user($dbc, $_GET['id']); }
		
		break;`

I thought it might have been an issue with the form as the data is not loading into the form once selecting a user but it seems fine

`<form action="index.php?page=users&id=<?php echo $opened['id']; ?>" method="post" role="form">
            
                <div class="form-group">
                    <label for="firstname">First Name:</label>
                    <input type="text" class="form-control" id="firstname" value="<?php echo $opened['firstname']; ?>" name="firstname" placeholder="First Name">
                </div>
                
                <div class="form-group">
                    <label for="lastname">Last Name:</label>
                    <input type="text" class="form-control" id="lastname" value="<?php echo $opened['lastname']; ?>" name="lastname" placeholder="Last Name">
                </div>
                
                <div class="form-group">
                    <label for="status">Status:</label>
                    <select class="form-control" id="status" name="status">
                    
                        <option value="0" <?php if(isset($_GET['id'])){ selected('0', $opened['status'], 'selected'); } ?>>Inactive</option>
                        <option value="1" <?php if(isset($_GET['id'])){ selected('1', $opened['status'], 'selected'); } ?>>Active</option>
                        
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="text" class="form-control" id="password" value="" name="password" placeholder="Password">
                </div>
                
                <button type="submit" class="btn btn-success">Save</button>
                <input type="hidden" name="submitted" value="1">
                <input type="hidden" id="id" name="submitted" value="<?php echo $opened['id']; ?>">
            
            </form>`

I do not know which issue could be causing both the failure of the active state but also the form not loading content as everything up until this video is working as per the tests that Alan does through the tutorials.

I would really appreciate someone pointing out to me where I have made the mistake as I cannot see it despite it probably waving to me.  Thanks

**Comment by dbashby** [comment]
After stopping staring at the screen continuously I have realised a very large mistake so will close thios issue, fix what I have noticed and hopefully will get passed it.

**Comment by dbashby** [comment]
I am unsure whether this is the cause of ALL my issues but I have now found that there is an issue with my UPDATE query

`$q = "UPDATE posts SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]";`

I have returned to video 44 and checked and double checked against the code in the video and cannot see where the issue is.  I have tried the suggested solution in the comments under the video but that did not solve the issue either.

I am getting the following error

> Page could not be updated! because: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

UPDATE pages SET user = 3, slug = 'Test-slug', title = 'Test Title', label = 'Test Lable', header = 'Test Header', body = '

sdtqwerterywtyhwrtyhrtwy

' WHERE id =

So from what I can see it is only reading 1/2 of there WHERE clause but I cannot see why or where.

Grateful for any help!

Thanks

**Comment by dbashby** [comment]
The update query is triggering when I go to add a new page, for some reason it is ignoring the insert query.

`if(isset($_POST['id']) != 'null'){
			$action = 'updated!';
			$q = "UPDATE posts SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]";
		} else {
			$action = 'added!';
			$q = "INSERT INTO posts (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
		}
		
		
		$r = mysqli_query($dbc, $q);
		
		#Debug Query
		if($r){
			
			$message = '<p>Page was ' . $action . '</p>';
			
		} else {
		
			$message = '<p>Page could not be ' . $action . ' because: ' . mysqli_error($dbc);
			$message .= '<p>' . $q . '</p>';
			
		}
		
	}`

**Comment by dbashby** [comment]
If I take the query back to $_GET the new page submission works and it is added to the side menu/navigation however if I edit one of the other pages, the home page for example it adds another page as well.

**Comment by dbashby** [comment]
Link to code - http://pastebin.com/q2AzvBb6

Issue - This is my code from index.php from video 44
 
If I do not have null in the if(isset($_POST['id']) != ''){
 
I lose the ability to edit pages but I can add a new page
 
If I have null in the above then I can edit pages but I cannot add a new page
 
Any help appreciated!

Thanks

**Comment by creptor** [comment]
you should note that you use an `if(isset($_POST['id'])!=null){....` and then in the query you use `$_GET[id]`...

**Comment by dbashby** [comment]
Thanks, I tried the following but that does not work either.  I am assuming that you mean to use $_POST[id] at the end of the update query? 

After trying that I have lost both update and insert functionality on the form.

`if(isset($_POST['id']) != 'null'){
						$action = 'updated!';
						$q = "UPDATE posts SET 
							user = $_POST[user], 
							slug = '$_POST[slug]', 
							title = '$title', 
							label = '$label', 
							header = '$header', 
							body = '$body' WHERE id = $_POST[id]";
						
					} else {
						$action = 'added!';
						$q = "INSERT INTO posts (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
						
					}`

**Comment by creptor** [comment]
.-.

ok, then just place the code of the form... that way I can better understand what inputs you're submitting.

**Comment by dbashby** [comment]
The form code is at http://pastebin.com/wz5yL7ip

**Comment by creptor** [comment]
I found it... in the last input... the name is wrong.
the code (line 64-66):
```
<button type="submit" class="btn btn-success">Save</button>
<input type="hidden" name="submitted" value="1">
<input type="hidden" id="id" name="submitted" value="<?php echo $opened['id']; ?>">
```
should be:
```
<button type="submit" class="btn btn-success">Save</button>
<input type="hidden" name="submitted" value="1">
<input type="hidden" id="id" name="id<!-- THE NAME WAS WRONG-->" value="<?php echo $opened['id']; ?>">
```

**Comment by dbashby** [comment]
Thanks for that, saved me ripping what remains of my hair.

**Comment by dbashby** [comment]
I have corrected the line as you advised but I am still getting an error on UPDATE.

> Page could not be updated because: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

>UPDATE posts SET user = 4, slug = 'Test-slug', title = 'Test Title', label = 'Test Lable', header = 'Test Header', body = '

>testing the body

>' WHERE id =

**Comment by dbashby** [comment]
In the php code block for videos 43, 44 and ending with 45 where we create the queries.php page and past in the following block

`<?php
				
if(isset($_POST['submitted']) == 1){
	
	$title = mysqli_real_escape_string($dbc, $_POST['title']);
	$label = mysqli_real_escape_string($dbc, $_POST['label']);
	$header = mysqli_real_escape_string($dbc, $_POST['header']);
	$body = mysqli_real_escape_string($dbc, $_POST['body']);
	
	if(isset($_POST['id']) != 'null'){
		$action = 'updated';
		$q = "UPDATE posts SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]";
	} else {
		$action = 'added';
		$q = "INSERT INTO posts (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
	}
	
	
	$r = mysqli_query($dbc, $q);
	
	#Debug Query
	if($r){
		
		$message = '<p>Page was ' . $action . '</p>';
		
	} else {
	
		$message = '<p>Page could not be ' . $action . ' because: ' . mysqli_error($dbc);
		$message .= '<p>' . $q . '</p>';
		
	}
	
}

?>`

If I have the single quotes empty in the initial if(isset()) I can edit a page however I cannot create 1 as I get the sql error saying UPDATE has an error in it.  It should be using the INSERT query, yes?

If I put the null in the quotes I cannot edit a page, it creates a new one and if I select create a new page and complete the form I get a new page as expected.

Any ideas as to where the issue could be?

`if(isset($_POST['id']) != 'null'){
		$action = 'updated';
		$q = "UPDATE posts SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]";
	} else {
		$action = 'added';
		$q = "INSERT INTO posts (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
	}`


Thanks

**Comment by dbashby** [comment]
The message returned upon the error is showing that it is not seeing the $_GET[id] but as this error is only triggered if I have 'null' instead of '' there cannot be an error in my sqli, right?

**Comment by dbashby** [comment]
A mix of Creptor and McDuck74 fixed the issue, see https://github.com/thedigicraft/Atom.CMS/issues/63#issuecomment-190477657 for McDuck74 solution.

Thanks to both of you!
