### ISSUE TITLE
Pages & users - Reassigning a variable

### ISSUE THREAD

**Issue by dbashby** [thedigicraft/Atom.CMS#173]
After looking through the forums I came across https://github.com/thedigicraft/Atom.CMS/issues/50 and this is the same problem I am having as listed in https://github.com/thedigicraft/Atom.CMS/issues/172

The way that Zinadore solves it is by reassigning that $page variable but to be honest it is not clear exactly what Zinadore did.  Could someone possibly say what $pages = ?

Thanks

**Comment by creptor** [comment]
please try to keep every issue by itself... repeated issues could create more false issues, because of incomplete answers for the same problem witch could be already solved. And the redirects are kind of annoying. See issue #172
