### ISSUE TITLE
Page manager not properly working

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#177]
So basically, the pages still save on the admin end, but won't update to the front end. I tried to ediit one of the pages and I can tell that there's some disconnection somewhere. For instance, if I change the page names and everything, I still have to go onto phpmyadmin to change the url or else it doesn't work. As for new pages, it would seem as though I would need to manually put it into phpmyadmin before creating the page. In reality it wouldn't be too much of a hassle, but from my memory it worked just fine before.. :'( So plz Digicraft.. Fix my web..

**Comment by Chriswilldo** [comment]
It's been since last June since I worked on this. Thought it wasn't finished, but then remmebered that I was trying to use the new dropzone on this website and something else.

**Comment by JorgeBautista** [comment]
Came to open a  new issue on the same problem, adding or editing pages, nothing happens on the front end.
![site1](https://cloud.githubusercontent.com/assets/15808004/13889750/4f285e26-ed16-11e5-97ab-7a0e75894325.png)
![site2](https://cloud.githubusercontent.com/assets/15808004/13889754/55e537c0-ed16-11e5-8757-cabe6ad69ed6.png)
![site3](https://cloud.githubusercontent.com/assets/15808004/13889758/5c4b057c-ed16-11e5-90ac-b731ef899472.png)

**Comment by creptor** [comment]
try looking into issue #172, maybe that's your problem.

**Comment by Chriswilldo** [comment]
idk exactly what you mean. Based on my understanding, my setup.php looks fine. It might be something else. Because when I delete the page it shows it deleted in firebug, but not on the page. Also when i add the page it doesn't have have that php style like it should. It's just a basic green. It might have something to do with the coding there perhaps? Sorry I haven't done this in a while so it's kind of a pain to find exactly where the problem is. Heres my setup.php and the pages part of queries.php. I'll be sure to check the final coding as well.

**Comment by Chriswilldo** [comment]
![queries php](https://cloud.githubusercontent.com/assets/8390023/13907430/1665ce28-eebc-11e5-9edc-f12ae77161e4.JPG)
![setup php](https://cloud.githubusercontent.com/assets/8390023/13907431/1667c764-eebc-11e5-8425-5ae40ecffb66.JPG)

**Comment by creptor** [comment]
Please use something like http://pastebin.com/ to submit your code, images are just too slow, and a paint. Also please include setup.php, query.php and the page administration page.

**Comment by creptor** [comment]
Sorry for the delay, I forgot I had this issue sent to my email, and that it was marked read.

**Comment by creptor** [comment]
O and please upload the Ajax files, if you want help with those

**Comment by Chriswilldo** [comment]
http://pastebin.com/u/Chriswilldo

**Comment by Chriswilldo** [comment]
I put whole ajax folder files into one to save time and space since most of them were only a paragraph of code

**Comment by creptor** [comment]
Does your page contents are filled when you select the page (when editing)?

**Comment by creptor** [comment]
I got this version of your `query.php` fixed (only for pages, you must fix the rest), and I couldn't fix the ajax, because no javascript was included in the files you gave me (for the pages administration page).

http://pastebin.com/ZFK0b2Dx

**Comment by Chriswilldo** [comment]
Well thank you still. The page still gets created and filled and everything, it's just it doesn't get added to the front end unless if I manually add it in like how you taught when first building the site. Then it works. Which in all isn't all that  bad. At least it works right? I can still edit it on the admin and afterwards and it'll still work just fine, I just have to manually input the page on phpmyadmin

**Comment by creptor** [comment]
You should then check that the myqli is returning no errors.... that can further help you building a site.

Also you should enable php errors hardcoded to your script, to be sure that it's enabled. Just add an `error_reporting(-1);` to the start of the fiel, it will return more detailed information about php errors. This can make it easy to fix.

I also recommend that you upload your javascript, because maybe the ajax was working instead of the `query.php` (that's fixed), and that the ajax is making that awful result.

**Comment by queky18** [comment]
Hello friends, 

Have you fixed your isssues ? because I get the same problem , and I can't fix it ..

**Comment by creptor** [comment]
Please create a new issue with your code... The problems that involves database connection usually aren't related, or have a different way of fixing.
