### ISSUE TITLE
Update works fine but new page query SQL not working

### ISSUE THREAD

**Issue by dbashby** [thedigicraft/Atom.CMS#19]
I have posted the code from all the relevant pages from the admin section at https://github.com/dbashby/code.git 

I have gone through 44 and 45 several times to see if I have missed anything, I even copied and pasted the queries from Digicraft to see if I had made a typo but I cannot see the issue.

The error I am getting is 

Page could not be updated because: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

UPDATE pages SET user = 1, slug = '', title = 'Test', label = '', header = '', body = '

test

' WHERE id =

Any help would be appreciated.  Thanks

**Comment by RosemaryRoss** [comment]
dbashby,
If you have the code working from video 44, could you please share it??  I'm going cross eyed trying to figure out my mistake.  Thank you.

Rosemary

**Comment by creptor** [comment]
@RosemaryRoss Create a new issue if you can't get something to work, maybe it's the same one but it's a year old.
