### ISSUE TITLE
Developing a Dynamic Website (CMS) from Start to Finish

### ISSUE THREAD

**Issue by bghodsi** [thedigicraft/Atom.CMS#195]
Hi Alan:
Attached is the complete application in a zipped format .

Please refer to my previous post for additional info.
 Few facts:

I use local server.
database name is different than yours. please see connection.php.

Your suggestions will be greatly appreciated.

Bob Ghodsi

**Comment by bghodsi** [comment]
Blog works fine but when I click on a title always the last record in the database pops up.

any suggestion will be appreciated.

**Comment by creptor** [comment]
Was your issue really been solved?
