### ISSUE TITLE
Last attempt to upload the link

### ISSUE THREAD

**Issue by bidjan** [thedigicraft/Atom.CMS#203]
Hi creptor:

below is the url to blog.php. As I explained to you before everytime I click on  title on the left the form that shows up on the right is always the last record.

I  am hoping I am getting this done right!!

Bob Ghodsi
http://pastebin.com/xyvKb654

**Comment by creptor** [comment]
jajajajaj it was soo simple 😋, well now you know how to use GitHub 👍 

To fix your code just look at line `56` and replace this ->
```
$q="SELECT * FROM blog  ORDER BY date DESC";
```
**With this ->**
```
$q="SELECT * FROM blog WHERE id = $_GET[id]";
```

> This actually uses the variable you have in your url

**Comment by creptor** [comment]
If you have another issue feel free to ask 😋

**Comment by bidjan** [comment]
Hi Creptor:
Thank you for correcting my code.  Big relief!
You live and learn!

You are right, It is so simple when you know what you are doing.

Bob Ghodsi
