### ISSUE TITLE
2014 dynamic CMS (Navigation.php in Admin)

### ISSUE THREAD

**Issue by bidjan** [thedigicraft/Atom.CMS#206]
Attached is navigation.php that fails to show dropdown menu in bootstrap.

The coding has been checked several times but it still fails to produce the desired result.

Please let me know if there is anything I am doing wrong.

Bob Ghodsi

http://pastebin.com/xyc42fqS

**Comment by creptor** [comment]
First... Make sure that you're using the JavaScript included in the bootstrap folders.

After that I recommend you change the drop down html code with this:
```
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
```

If it doesn't work, please replace the JavaScript (for bootstrap) with this code:
```
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

**Comment by bidjan** [comment]
Hi Creptor:
Thank you for the tip. Wrong javascript as you suggested. 
 Question :

Do I have to keep this in the script itself. Seems to be unnesessary.
integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"

**Comment by creptor** [comment]
Here is a website that explains what's that for.

https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/
