### ISSUE TITLE
2014 dynamic CMS  

### ISSUE THREAD

**Issue by bidjan** [thedigicraft/Atom.CMS#209]
Hi creptor:

Attached are sandbox.php & .htaccess.

The problem I am having is whenever I insert .htacces  into the mix when I run index.php in front and back (admin)  I get server error!!.  

I hand coded sandbox.php as I could not get the correct url to copy and paste it..

What am I doing wrong?

Thanks

http://pastebin.com/fk6XXSmK

**Comment by bidjan** [comment]
I finally got hold of the cod. I replaced what I had in the mix with new sandbox. All is well so far.

Please disregard this message

**Comment by creptor** [comment]
No problem 😋

**Comment by creptor** [comment]
Next time, if you can't fix it and it's tossing an error message, please copy it here (exactly at it's shown)
