### ISSUE TITLE
part 15: My image won't load...

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#225]
help me please. I hate coding so much... >:'\

**Comment by Chriswilldo** [comment]
for some reason it keeps loading in aptana as a document not an image. Whether i paste in manually or automatically (copy and paste into aptana). Everything else has been on point more or less.

**Comment by Chriswilldo** [comment]
Nvm........................................................................................................................................

letter errors as usual!!!!

BE SURE TO DOUBLE CHECK AND SAVE EVERY OTHER MINUTE!!!!

**Comment by creptor** [comment]
it happens 😋
