### ISSUE TITLE
PArt 79: Image won't change dynamically

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#226]
It's not the biggest issue in the world, but it'd be nice if I could get it to work. If i can't, I'll just move on. It's not a big deal anyways. If anyone could help me, I'd greatly appreciate it. It works, I just have to refresh. However it's been working like that since part 78 like it correctly should. My brain is fried right now and I'm completely lost.

**Comment by Chriswilldo** [comment]
If you could please specify what coding you need to look at also, I'd greatly appreciate it. My mind is not working right now...

**Comment by creptor** [comment]
ok I need to have these files:
```
admin/ajax/avatar.php
admin/view/users.php
```
With the version of the Dropzonejs and an user image directory (example: 'root/images/users/myimage.jpg').

With that I think I can fix it :yum:

**Comment by Chriswilldo** [comment]
Avatar.php
`<?php 

include('../../config/connection.php'); 

$id = $_GET['id'];

$q = "SELECT avatar FROM users WHERE id = $id";
$r = mysqli_query($dbc, $q);

$data = mysqli_fetch_assoc($r);

?>

<img src="../uploads/<?php echo $data['avatar']; ?>">	
`

**Comment by Chriswilldo** [comment]
Finally had some food in my tummy, so I can think a bit clearer hahaha.

`<?php if(isset($opened['id'])) { ?> 
<script>
		
$(document).ready(function() { 
	
	Dropzone.autoDiscover = false;
	
	var myDropzone = new Dropzone("#avatar-dropzone");

myDropzone.on("success", function(file) { 
	
	$("#avatar").load("ajax/avatar.php?id=<?php echo $opened['id']; ?>");
	
});

	});	
	
</script>
<?php } ?>

<h1>User Manager</h1>

<div class="row">

<div class="col-md-3">
	
<div class="list-group">	
	
<a class="list-group-item" href="?page=users">
	
	<i class="fa fa-plus"> </i> Add User
		
</a>	
			
<?php 

$q = "SELECT * FROM users ORDER BY last ASC";
$r = mysqli_query($dbc, $q);
while($list = mysqli_fetch_assoc($r)) { 
$list = data_user($dbc, $list['id']);
	
	//$blurb = substr(strip_tags($list['body']), 0, 140);
	
	?>


	
<a class="list-group-item <?php selected($list['id'], $opened['id'], 'active') ?>" href="index.php?page=users&id=<?php echo $list['id']; ?>">
	
	<h4 class="list-group-item-heading"><?php echo $list['fullname_reversed']; ?></h4>
	
		
	
</a>
	
<?php } ?>

</div>			
			
		</div>
		
		<div class="col-md-9">
			
	<?php if(isset($message)) { echo $message; } ?>				
	
			<?php if($opened['avatar'] != '') { ?> 
			
<div id="avatar">
	
			<img src="../uploads/<?php echo $opened['avatar']; ?>">	
	
</div>			
				
				<?php } ?>
			
				<form action="index.php?page=users&id=<?php echo $opened['id']; ?>" method="post" role="form">
							
			<div class="form-group">
				
				
		<label for="first">First Name:</label>
		<input class="form-control" type="text" name="first" id="first" value="<?php echo $opened['first']; ?>" placeholder="First Name" autocomplete="off"/>		
				
			</div>
			
			<div class="form-group">
				
				
		<label for="last">Last Name:</label>
		<input class="form-control" type="text" name="last" id="last" value="<?php echo $opened['last']; ?>" placeholder="Last Name" autocomplete="off"/>		
				
			</div>
			
			<div class="form-group">
				
				
		<label for="email">Email Address:</label>
		<input class="form-control" type="text" name="email" id="email" value="<?php echo $opened['email']; ?>" placeholder="Email Address" autocomplete="off"/>		
				
			</div>
			
			<div class="form-group">
				
				
		<label for="status">Status:</label>
		<select class="form-control" name="status" id="status">
			
				<option value="0" <?php if(isset($_GET['id'])) { selected('0', $opened['status'], 'selected'); } ?>>Inactive</option>
				<option value="1" <?php if(isset($_GET['id'])) { selected('1', $opened['status'], 'selected'); } ?>>Active</option>	
			
		</select>		
				
			</div>
			
		<div class="form-group">
				
				
		<label for="password">Password:</label>
		<input class="form-control" type="password" name="password" id="password" value="" placeholder="Password" autocomplete="off"/>		
				
			</div>
			
			<div class="form-group">
				
				
		<label for="passwordv">Verify Password:</label>
		<input class="form-control" type="password" name="passwordv" id="passwordv" value="" placeholder="Verify Password" autocomplete="off"/>		
				
			</div>	
	
<button type="submit" class="btn btn-warning">Save</button>
	<input type="hidden" name="submitted" value="1" />					
			<?php if(isset($opened['id'])) { ?> 
		<input type="hidden" name="id" value="<?php echo $opened['id']; ?>" />		
		<?php } ?>		
				</form>
				
<?php if(isset($opened['id'])) { ?> 				
				
	<br>
	 
	<form style="background:url(images/spritemap.png)" action="uploads.php?id=<?php echo $opened['id']; ?>" class="dropzone" id="avatar-dropzone">
		
		<br><br><br><br><br>
	
	</form>
	
	<?php } ?>
			
	<br>

	</div>`

**Comment by Chriswilldo** [comment]
users.php
https://gist.github.com/Chriswilldo/9362c57a770fd48d53b399b7e7dabdbf

**Comment by Chriswilldo** [comment]
https://gist.github.com/Chriswilldo/80f3ff06a0da0ace13357ba9da020af0

**Comment by Chriswilldo** [comment]
I'm using the newest dropzone.js that they currently have on their website. the image directory is LastCMS/uploads i believe. Again, it worked at part 78 just fine, but part 79 wasn't changing it instantaneously. It still works after a refresh, but you know. I want it to be just like yours!!!!

**Comment by creptor** [comment]
Well, I couldn't catch any problems with your code, maybe you should try to see where the error is.
It's quite simple, just follow this tutorial on chrome (it's a web file, no virus, just dismiss the alerts).

[console debugging.zip](https://github.com/thedigicraft/Atom.CMS/files/738123/console.debugging.zip)

Note: Some things are in spanish due to operating system language. (read the notes)

Then please send me what you have gotten on the console, it would be easier for me to find the error.

> Please while debugging upload an image, so the hole process is recorded on the console, if no error is given, please send screenshot of the 'network' tab in the developer console.

**Comment by Chriswilldo** [comment]
ah man.. I'll try redoing everything from part 79 one more time. Sometimes that helps i guess. Especially with $q = $r= $data = . Idk why but they always give me the most trouble if  I don't put them in correctly the first time. I kind of figured i'd have problems. I could of sworn last time I did this I got it to work, but I ended up losing that laptop : '( . Worst case scenario I'll just leave it as is. It's not the end of the world. Rofl all I have to do is just press refresh.

**Comment by Chriswilldo** [comment]
Welp. I'm just gonna finish the site to the best of my ability, and if I feel like it , I'll get back to this part. I already wasted to much time on a technicality .

**Comment by creptor** [comment]
Yes, I would recommend that you get working all the php scripts after adding fancy JavaScript to make it feel more like an application.

Besides after that it should be easier to do that, because you will be sure how the application should feel like.
