### ISSUE TITLE
Further processing of teaxtarea text

### ISSUE THREAD

**Issue by mtaziz123456789** [thedigicraft/Atom.CMS#227]
I want to ask that can I use PHP tags inside body data? 
![screenshot 1](https://cloud.githubusercontent.com/assets/26614903/24231041/14b69a62-0fa4-11e7-9076-ab9505baec71.png)
I want to use some PHP functions (such as echo) or some mysql queries (such as select) instead of plane text in the above screenshot within square brackets . Please answer (keeping in view that this plane text as saved in a column of a mysql table).  Is it possible?
![screenshot 2](https://cloud.githubusercontent.com/assets/26614903/24245418/9b77ee44-0fe4-11e7-9ef7-77a620451cc7.png)
I want to ask that in that body textarea of a table's column is it possible to use php and mysql queries

**Comment by creptor** [comment]
You need to handle the data from the database differently, please wait, I'll post an example when I can...

**Comment by creptor** [comment]
I think the thing you're looking for is called ´eval()´, but you should really understand the risk of using it, please browser the web for more reference.

You can read more about ´eval()´ in these pages:
http://stackoverflow.com/a/10866400
http://php.net/manual/en/function.eval.php

Keep this in mind, It's a quote:
> If eval() is the answer, you're almost certainly asking the wrong question.
> - Rasmus Lerdorf, BDFL of PHP

PD:
Sorry for the delay, I needed to study for a test...

**Comment by mtaziz123456789** [comment]
Thanks for help let me try this
