### ISSUE TITLE
css positioning problem

### ISSUE THREAD

**Issue by v917** [thedigicraft/Atom.CMS#231]
My test debug window is coming on top of the footer. I had also put its position: absolute and once position: relative but nothing happened. The jquery hiding feature is working perfectly but this position of debug window is messing all this. Please Help. Thanks in advance.

**Comment by creptor** [comment]
Can you please upload the `index.php` file and the `.CSS` that you're using?

It would help me figure out the problem if you also take a screenshot of the site, to see how it's behaving.

> Note: if the debug window is not inside the `index.php` file, please upload the file that contains it.

**Comment by v917** [comment]
**index.php**


`<?php include('config/setup.php');?>  

<!DOCTYPE html>
<html>
	<head>
		
		<title><?php echo $page['title'].'|'.$site_title?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php include('config/css.php'); ?>
	    <?php include('config/js.php'); ?>
		
	</head>
	
	<body>
	<div id="wrap">	
			
		<?php include(D_TEMPLATE.'/navigation.php'); ?>
		
		
		<div class = "container">
		
		<h1><?php echo $page['header']; ?></h1>
		<?php echo $page['body_formatted'];?>
		
		</div>
	
	</div>
		
		<?php include(D_TEMPLATE.'/footer.php'); ?>
		
		<?php if($debug == 1) { include('widgets/debug.php'); } ?>
			
			
		</body>
</html>
`




**css.php**

<?php
//CSS:
?>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
			

<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
			

<script src="https://use.fontawesome.com/e9c36b76e7.js"></script>
			
<style>
/* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
#footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #f5f5f5;
}

#btn-debug {
	position: absolute;
}

#console-debug {
	position: absolute;
	top: 50px;
	left: 0px;
	width: 30%;
	height: 500px;
	overflow-y: scroll;
	background-color: #FFFFFF;
	 box-shadow: 2px 2px 5px #888888;
}

#console-debug pre {
}

/* Custom page CSS
-------------------------------------------------- */
/* Not required for template or sticky footer method. */

.container {
  width: auto;
  max-width: 680px;
  padding: 0 15px;
}

</style>



**output:**

 
[AtomOutput.docx](https://github.com/thedigicraft/Atom.CMS/files/907620/AtomOutput.docx)

**Comment by creptor** [comment]
So you want the debug window to extend to the bottom of the page, over the footer right?

**Comment by creptor** [comment]
If that's the case change the `#console-debug` `height:500px;` option with:

`bottom:0;`

**Comment by v917** [comment]
**index.php**: https://pastebin.com/yKbtiguj
**css.php**: https://pastebin.com/Tbtws0FS
**output**: [AtomOutput.docx](https://github.com/thedigicraft/Atom.CMS/files/907656/AtomOutput.docx)

**Comment by v917** [comment]
ok thanks
