### ISSUE TITLE
links of nav bar are not working (Part - 54)

### ISSUE THREAD

**Issue by v917** [thedigicraft/Atom.CMS#233]
After making `pages.php`, `users.php` & so on, the text **Dashboard** is coming only on loading the page for the first time and after that clicking on any link(even dashboard as well) will end up showing blank screen. I thought watching next video will resolve my issue but i was wrong. I am not even getting the **Page Manager** page. Please help.
**pages.php:** https://pastebin.com/5YygjWsD
**index.php:** https://pastebin.com/9Wu1W8HS
[Page loading for the first time.docx](https://github.com/thedigicraft/Atom.CMS/files/912542/Page.loading.for.the.first.time.docx)

**Comment by creptor** [comment]
Your navigation links are wrong.... They should redirect the user to: `?Page=[page_name]` instead of `?age=`

**Comment by creptor** [comment]
Sry, I clicked comment before I finished it.

Your navigation links are wrong, they should redirect the user to: `?page=[page_name]` instead of `?page=[page_name].php`.

**Comment by v917** [comment]
Yes, I have typed `?page=pages` not `?page=pages.php`. See here below:
`<a class="list-group-item" href="?page=pages"> <i class="fa fa-plus"></i>&nbsp;New Page </a>`

**Comment by v917** [comment]
Here is **navigation.php:** https://pastebin.com/hMSWSwQy if needed to check.

**Comment by creptor** [comment]
The pastebin code shows that you're using `?page=example.php`.

You have to change that to `?page=example`

**Comment by v917** [comment]
I don't understand where are you saying to change because the **pages.php** contains `?page=example` as you are saying to do and I have recheck the pastebin code as well. And if you are saying to do this change in **navigation.php** then on clicking any link how would it navigate to the clicked page. Please elaborate, I am confused now.

**Comment by v917** [comment]
@creptor Because of this issue I am unable to move forward. Please help.

**Comment by v917** [comment]
@creptor  Ok Ok.. Done.. Issue resolved.. I have done the change in `navigation.php` and now it is working and I have also understood the logic behind. Thank You So Much for your help.

**Comment by v917** [comment]
@creptor Ok Ok.. Done.. Issue resolved.. Thank You So Much for your help. I have done the change in navigation.php and now it is working and but I didn't get the logic behind.

**Comment by v917** [comment]
@creptor Ok Ok.. Done.. Issue resolved.. Thank You So Much for your help. I have done the change in navigation.php and now it is working.

**Comment by creptor** [comment]
Right... I didn't say it was the navigation.php file, I'm sorry if it took long to figure it out. 😔

**Comment by v917** [comment]
It's ok.. at least you replied to my issue..
