### ISSUE TITLE
The placeholder is not displaying correct value (Part - 65) 

### ISSUE THREAD

**Issue by v917** [thedigicraft/Atom.CMS#234]
Hi, @creptor actually the label textboxes in `setting.php` are not displaying the text which is in database, instead it is displaying **Label**. Please Help.

**settings:** https://pastebin.com/npgQdZrA
**queries.php:** https://pastebin.com/7dRuvqgB
[Label problem.docx](https://github.com/thedigicraft/Atom.CMS/files/920142/Label.problem.docx)

**Comment by v917** [comment]
ok, problem solved.

**Comment by creptor** [comment]
Sorry for not being able to attend your issue, I was too busy with the university.

**Comment by creptor** [comment]
😢

**Comment by v917** [comment]
ohh its totally fine. Don't be sad

**Comment by v917** [comment]
@creptor but now I am having another problem that, it is showing the message "Setting was updated" but it is not actually updating it. So, whenever you'll be free then resolve my issue. Till then I am moving forward to next video.
**queries.php:** https://pastebin.com/PciCyMKi
**settings:** https://pastebin.com/Yn37iXGN

**Comment by creptor** [comment]
I think that this:
```
$q = "UPDATE settings SET id = '$_POST[id]', label = '$label', value = '$value' WHERE id = '$_POST[openedid]'";
```
Should be:
```
$q = "UPDATE settings SET id = '$_POST[id]', label = '$label', value = '$value' WHERE id = '$_POST[id]'";
```

**Comment by v917** [comment]
But I have used `<input type="hidden" name="openedid" vaule="<?php echo $opened['id']; ?>" />` that is why it is `'$_POST[openedid]'`

**Comment by creptor** [comment]
Try changing this:
```
if(isset($_POST['id']) != '') {
```
With:
```
if(isset($_POST['openedid'])&&$_POST['openedid']!='') {
```

**Comment by v917** [comment]
No it is not working. See here:

![image](https://cloud.githubusercontent.com/assets/22052958/25034583/7955e082-209c-11e7-9473-4816291f4d7c.png)

And sorry for disturbing you in your busy schedule.

**Comment by v917** [comment]
Now, I am having similar problem in navigation link as well. It is also showing updating message but not actually updating it.
![image](https://cloud.githubusercontent.com/assets/22052958/25049391/77ca7a5c-20f6-11e7-82d1-ff525a50b8ed.png)

**Comment by v917** [comment]
I am not able to move forward now. Please Help @creptor if you are free.

**Comment by creptor** [comment]
Please add this to the top of the file (inside setup.php would do fine) to try to find an error:
```
error_reporting(E_ALL);
ini_set("display_errors", 1);
```

If there's any error, it should be output as text. Check the console, the might be found behind elements with styles.

**Comment by v917** [comment]
Nothing happened 😢

![image](https://cloud.githubusercontent.com/assets/22052958/25059399/0be1c79c-213b-11e7-89ea-24f378e328d9.png)

**Comment by v917** [comment]
@creptor Why this is happening to me? 😢

**Comment by creptor** [comment]
Can you take a photo of the database structure? To find out if the query is wrong...

**Comment by v917** [comment]
ok wait

**Comment by v917** [comment]
[DatabaseScreenshots.docx](https://github.com/thedigicraft/Atom.CMS/files/923186/DatabaseScreenshots.docx)
Check it Now

**Comment by v917** [comment]
[db.docx](https://github.com/thedigicraft/Atom.CMS/files/923194/db.docx)

If you need this one as well then please check.

**Comment by creptor** [comment]
can you please put the query for the pages and users here?

**Comment by creptor** [comment]
Also you could try with this query:
´´´
$q = 'UPDATE settings SET id = '.$_POST['id'].', label = '.$label.', value = '.$value.' WHERE id = '.$_POST['openedid'];
´´´

**Comment by v917** [comment]
After changing what you said to do, this happened:
![image](https://cloud.githubusercontent.com/assets/22052958/25059818/9bf9dcfa-2142-11e7-9bf7-155148e7a006.png)

**Comment by v917** [comment]
And queries for pages and users are: https://pastebin.com/WK6Nj3Pn

**Comment by v917** [comment]
I want to ask one thing that:
`<input type="hidden" name="openedid" vaule="<?php echo $opened['id']; ?>" />`


` $q = 'UPDATE settings SET id = '.$_POST['id'].', label = '.$label.', value = '.$value.' WHERE id = '.$_POST['openedid'];;`

here in input tag openedid is the name and and in the query i am searching `id =  '$_POST[openedid]'`, So is it correct?

**Comment by creptor** [comment]
Try changing the query to this:
```
$q = 'UPDATE settings SET id = `'.$_POST['id'].'`, label = `'.$label.'`, value = `'.$value.'` WHERE id = `'.$_GET['id'].'`';
```

> The `$_POST['openedid']` is not being set correctly, so this will fall back to the id sent by the URI.

**Comment by v917** [comment]
ok. Wait

**Comment by creptor** [comment]
> here in input tag openedid is the name and and in the query i am searching id = '$_POST[openedid]', So is it correct?
Could you please rephrase that, I didn't understand 😢 .

**Comment by v917** [comment]
Nothing happened again

![image](https://cloud.githubusercontent.com/assets/22052958/25059889/6e54955e-2144-11e7-8510-a23012d7143e.png)

**Comment by creptor** [comment]
Sorry, I think it was the other way around, try this:
```
$q = "UPDATE settings SET `id` = '".$_POST['id']."', ´label´ = '".$label."', ´value´ = '".$value."' WHERE ´id´='".$_GET['id']."'";
```

**Comment by v917** [comment]
o/p:

![image](https://cloud.githubusercontent.com/assets/22052958/25059943/a6d24894-2145-11e7-8ad6-6579d01cc567.png)

**Comment by creptor** [comment]
can you check if the input that is hidden with the value ´openedid´ has the same value has the id one?

**Comment by v917** [comment]
**queries.php** https://pastebin.com/RG0FPDB3
**settings.php** https://pastebin.com/gNxzGWRx
**pages.php** https://pastebin.com/Q2iuw2Sq

**Comment by v917** [comment]
ok, wait.

**Comment by v917** [comment]
yes @creptor the input that is hidden with the value ´openedid´ is same as the id.

**Comment by creptor** [comment]
This might be the one, it looks similar to the above one, but I was using the Latin keyboard, so the symbols where `invalid` on US machines 🤦‍♂️ , check if it now works:
```
$q = "UPDATE settings SET `id` = '".$_POST['id']."', ´label´ = '".$label."', ´value´ = '".$value."' WHERE ´id´='".$_POST['openedid']."'";
```

**Comment by v917** [comment]
ok wait

**Comment by v917** [comment]
no, again... same error...
 
could you please insert this query in `queries.php` because I think it's again your latin keyboard.

**Comment by v917** [comment]
Is `´` correct ? because i have not seen `´` before.. Is it coming from your latin keyborad or you actually wanted to use this?

**Comment by creptor** [comment]
.-. ok this should be correct (I actually copied the symbol so.... yea):
```
$q = "UPDATE settings SET `id` = '".$_POST['id']."', `label` = '".$label."', `value` = '".$value."' WHERE `id`='".$_POST['openedid']."'";
```

>Is ´ correct ? because i have not seen ´ before.. Is it coming from your latin keyborad or you actually wanted to use this?

Yea, that thing is confusing as fuck if you want to us it 👎 

-----
after this the problem should be elsewhere if it persists.

**Comment by v917** [comment]
but this query is same as you gave before

**Comment by v917** [comment]
ok leave 😢. And thank you so much for your help. Really thanks a lot.

**Comment by creptor** [comment]
that's the thing, nothing that I have found in your script was wrong, so you need to patch the errors or better called 'inconsistencies' to see if it starts working. If I'm not mistaken you should use the symbol ``` for enclosing table names, so there's that.

For example, instead of:
```
if(isset($_POST['id']) != '') {
```
You should actually use:
```
if(isset($_POST['id'])&&$_POST['id']!='') {
```

**Comment by creptor** [comment]
Wait, I can actually create another code to make it work, but  it will be different. I use other things that are more.... advanced? any way, I can't explain to you how the code will work that's the catch, but it would be basically the same thing and it should work.

**Comment by creptor** [comment]
I will make it tomorrow if you tell me the credentials that you're using for the database:

Example:
user: root, password: ,host: (localhost?),port: (3306?)

**Comment by v917** [comment]
You have told me to use `if(isset($_POST['id'])&&$_POST['id']!='')` before but it didn't work. And told you about that. And thanks for doing so much for me.

**Comment by v917** [comment]
ok wait.

**Comment by v917** [comment]
user: Dev
password: password1
host: localhost
port: 80

Is that what you are asking?

**Comment by creptor** [comment]
I need the information of the database, port 80 is used for web interface.

**Comment by creptor** [comment]
what you have inside of the file `database.php`, if you want you can email it to me to keep it secret... this is my email: creptor@live.com

**Comment by v917** [comment]
ok

**Comment by v917** [comment]
I have mailed you. Please tell me if i have send you exactly what you are asking or not.

**Comment by creptor** [comment]
yes it's correct 👍 I'll email you the solution when I finish it 😋

**Comment by v917** [comment]
ok, Thank you so much in advance

**Comment by creptor** [comment]
This makes me feel stupid, but now I know where the mistake is. Just an annoying typo... Please change this:
```
vaule="etc..."
```
To
```
value="etc..."
```
> Note that it's spelled `value` not `vaule`, that's why the input returns empty.

This mistake is found in the `submitted` and `openedid` input 😀

**Comment by v917** [comment]
A very very big thanks to you @creptor. And I really mean it because I had loosed the hope to complete this series but you didn't give up. Thank you so much for your precious time. Really thanks a lot.

**Comment by creptor** [comment]
No problem, I'm glad I could help!

I'll be here if you still have issues 👍.
