### ISSUE TITLE
Navigation problem (part - 91)

### ISSUE THREAD

**Issue by v917** [thedigicraft/Atom.CMS#235]
Hi, @creptor sorry for bothering you again. 
I am changing home and about-us positions and it's working:

![image](https://cloud.githubusercontent.com/assets/22052958/25068478/20848754-221a-11e7-8263-7bf363255aca.png)
   

but it is not working here:

![image](https://cloud.githubusercontent.com/assets/22052958/25068480/367b37ec-221a-11e7-8b22-0d7189e42de4.png)
  

I have even refreshed after changing their positions. And this time there are no typing errors as well.

**Comment by v917** [comment]
**list-sort.php:** https://pastebin.com/ZC3ZHN7C

**Comment by creptor** [comment]
I'm sorry, I forgot I received an email with this issue. Were you able to fix it yourself?

**Comment by v917** [comment]
no

**Comment by v917** [comment]
Actually, I thought you (@creptor) are busy and I have already bothered you so much, so, decided to leave. But didn;t understand the problem yet.

**Comment by creptor** [comment]
well the idea of making the navigation on the admin page is for the admin to be able to reorder or add new links to the navigation bar on the visible site...

to understand your problem I need the header.php from the visible site, and the navigation.php settings from the admin part.

**Comment by v917** [comment]
I am asking the purpose of settings sir.

**Comment by v917** [comment]
Actually, i don't have header.php yet.

**navigation.php**  https://pastebin.com/37g1RQpW

**Comment by creptor** [comment]
could you please be more specific? Wich settings are you talking about?

**Comment by v917** [comment]
![image](https://cloud.githubusercontent.com/assets/22052958/25076761/9825fc66-22d8-11e7-8f40-85a423dee6fb.png)


Here see the settings link

**Comment by v917** [comment]
And this navigation is working on the admin correctly but not on the main site. This is the actual problem.

**Comment by creptor** [comment]
Ok I got confused.... The order of the elements (the items on the left) are the one not working, or the items on the left are the ones not working

**Comment by v917** [comment]
see the 1st comment of mine, then you will surely understand

**Comment by v917** [comment]
see here its working here:

![image](https://cloud.githubusercontent.com/assets/22052958/25076829/5ee5b1a2-22d9-11e7-873a-20d5ab3db88e.png)



And in Alan's video the order is changing on the below site as well, but mine is not working on the below site

![image](https://cloud.githubusercontent.com/assets/22052958/25076859/8eece1d6-22d9-11e7-9f22-75becfea7e6b.png)


Have you got my point now?

**Comment by creptor** [comment]
I think.... Can I see your ajax script?

**Comment by v917** [comment]
list-sort.php: https://pastebin.com/ZC3ZHN7C

**Comment by creptor** [comment]
mmmm.....  if you refresh the page, the changes are there or the order of the list returns to default?

**Comment by v917** [comment]
after refreshing i can see the changes

**Comment by creptor** [comment]
Does the database shows those changes??

**Comment by creptor** [comment]
please check

**Comment by v917** [comment]
![image](https://cloud.githubusercontent.com/assets/22052958/25077058/5514a8de-22db-11e7-9249-204f74b7887e.png)

**Comment by v917** [comment]
So, it's confusing now😕

**Comment by v917** [comment]
**template.php:**  https://pastebin.com/izup0pRY

template.php is also correct. I am not understanding what's wrong.

**Comment by creptor** [comment]
maybe try changing the position ASC to DESC, on the header.php... see if something changes

**Comment by v917** [comment]
are you talking about template.php?

**Comment by creptor** [comment]
sorry, I'm talking about the navigation.php

**Comment by v917** [comment]
OK

**Comment by v917** [comment]
no change

**Comment by creptor** [comment]
I'll try to help you tomorrow, it's kind of late now
cya 👋

**Comment by v917** [comment]
It's ok,  I know it's night in your city.😃
Actually in my city this is morning time..😁

**Comment by creptor** [comment]
can you change the ASC for DESC on the template.php file? to see if something changes...

**Comment by v917** [comment]
I did that as well but nothing happened..😔

**Comment by v917** [comment]
I saw that on the navigation link side after reordering the labels, the id value gets reorder accordingly but position value doesn't but in database change is displayed in position value. But on main visible site we are displaying label name with reference to the url of the page. We are not relating position to the main visible site.

Are you understanding what my point is?

**Comment by v917** [comment]
See in the below screenshot, I have replaced the labels of main visible site with position value and guess what, it worked. But the problem is, because with the help of navigation link we have changed only the position value that is why here ( below screenshot ), it is changing the position value (coming from navigation table ) and the content below remains intact because that is coming from the pages table.

 
![image](https://cloud.githubusercontent.com/assets/22052958/25110180/ccba3596-2396-11e7-98ca-57d3d1d2867e.png)

**Comment by creptor** [comment]
is the position an int or an varchar value? (please check the database for this, on structure)

**Comment by v917** [comment]
it is int

**Comment by creptor** [comment]
I have no idea why is not working properly, I'm sorry.

As a last effort you could change the engine used by the database to see if it fixes the problem, but I don't know why this is happening.

**Comment by v917** [comment]
It's okay and thank you so much for your help.
