### ISSUE TITLE
That Source Code Is Not Working, The connections and all are made but not working

### ISSUE THREAD

**Issue by AshrafAliS** [thedigicraft/Atom.CMS#236]
I tried to check with my system. I made all the database connections and all. But not working. Can you send me the working code please. My mail id is     fashionzone004@gmail.com
Please send me writing code please.
Thanks you

**Comment by Chriswilldo** [comment]
?.. Mind if I see your code? What part are u stuck on? Paste all your code on here https://gist.github.com/ specify what part your on so the creator can better help you. I'm just a fan ; if you will.

**Comment by creptor** [comment]
An error message would be appreciated, and should appear if the code is not working.

Please check if you have any.

**Comment by AshrafAliS** [comment]
![image](https://cloud.githubusercontent.com/assets/20774847/25801921/8db47cd0-340d-11e7-80d3-3f3fd33f75e1.png)
DB connection is done, inserting pages users is done by impoting sql,
but dont no what is missing.
when i check the source code in browser.
`<body>
	
	<div id="wrap">		
			
		<nav class="navbar navbar-default" role="navigation">
	
			<button id="btn-debug" class="btn btn-default"><i class="fa fa-bug"></i></button>
		
	<div class="container">	
		
		<ul class="nav navbar-nav">
			
						
			
		</ul>
		
	</div>
	
</nav>


</div>		

	<footer id="footer">
		
		<div class="container">
			<p>This is my footer.</p>
		</div>
		
	</footer>`

**Comment by AshrafAliS** [comment]
and also in admin panel inserting pages is also not working
![image](https://cloud.githubusercontent.com/assets/20774847/25802122/8fa88620-340e-11e7-824d-f437cd291c49.png)
Not fetching pages from DB,
And Also insert in not working

can u please mail me Source_Code in zipped file to fashionzone004@gmail.com
please

**Comment by creptor** [comment]
Technically everyone uses "custom" versions of script to run their particular website, the idea of using GitHub is that you can upload your script (any .php file) and we'll help you figure out the problem, or in last resort I can make a code that works with your site....

Please upload the 'atabase.php'and the pages that aren't working correctly.

**Comment by AshrafAliS** [comment]
There are so many .php files which should I send don't no which file not not executing properly
