### ISSUE TITLE
Part 50: Image not appearing 

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#237]
I don't know why, but at part 50 my image was no longer showing up properly. It still shows but it only shows the border of the picture.

https://gist.github.com/Chriswilldo/d2fe77d987e98535fac3e4f6b049c82c

**Comment by Chriswilldo** [comment]
Never mind. I had to hand type my sandbox.php and found an uneeded ; in the code.

**Comment by creptor** [comment]
Nice catch!
