### ISSUE TITLE
I have some issues when i tried to update pages, please help

### ISSUE THREAD

**Issue by Th3-Gh057** [thedigicraft/Atom.CMS#254]
For couple of days I have an error on my admin page, if I want to update the title or anything from an existing page when I hit the save button, the page is not updating but it create a new one with the same content as the existing one and instead of 'page was update' message I receive 'page was added' .. I put here queries.php and pages.php in the case someone can help me with this issue, thanks

 queries.php

```
<?php
	
	switch ($page) {
		
		case 'dashboard':
		
		break;
		
		case 'pages':
			
			if(isset($_POST['submitted'])&&$_POST['submitted'] == 1) {
				
				$title = mysqli_real_escape_string($dbc, $_POST['title']);
				$label = mysqli_real_escape_string($dbc, $_POST['label']);
				$header = mysqli_real_escape_string($dbc, $_POST['header']);
				$body = mysqli_real_escape_string($dbc, $_POST['body']);
				
				if(isset($_POST['id']) AND $_POST['id'] != '') {
					
					$action = 'updated';
					$q = "UPDATE pages SET user = $_POST[user], slug = '$_POST[slug]', title = '$title', label = '$label', header = '$header', body = '$body' WHERE id = $_GET[id]";
				} else {
					$action = 'added';							
					$q = "INSERT INTO pages (user, slug, title, label, header, body) VALUES ($_POST[user], '$_POST[slug]', '$title', '$label', '$header', '$body')";
				}
				
				
				$r = mysqli_query($dbc, $q);
				
				if($r){
					
					$message = '<p class="alert alert-success">Page was '.$action.'!</p>';
					
				} else {
					
					$message = '<p class="alert alert-danger">Page could not be '.$action.' because: '.mysqli_error($dbc);
					$message .= '<p class="alert alert-warning">Query: '.$q.'</p>';
					
				}
							
			}
			
			if(isset($_GET['id'])) { $opened = data_page($dbc, $_GET['id']); }
			
		break;
		
		case 'users':
			if(isset($_POST['submitted']) == 1) {
				
				$first = mysqli_real_escape_string($dbc, $_POST['first']);
				$last = mysqli_real_escape_string($dbc, $_POST['last']);
				
				if($_POST['password'] != '') {
					
					if($_POST['password'] == $_POST['passwordv']) {
						
						$password = " password = SHA1('$_POST[password]'),";
						$verify = true;
						
					} else {
						
						$verify = false;
						
					}					
					
				} else {
						
					$verify = false;	
					
				}
				
				if(isset($_POST['id']) != '') {
					
					$action = 'updated';
					$q = "UPDATE users SET first = '$first', last = '$last', email = '$_POST[email]', $password status = $_POST[status] WHERE id = $_GET[id]";
					$r = mysqli_query($dbc, $q);
					
				} else {
					
					$action = 'added';					
					$q = "INSERT INTO users (first, last, email, password, status) VALUES ('$first', '$last', '$_POST[email]', SHA1('$_POST[password]'), '$_POST[status]')";
					
					if($verify == true) {
						$r = mysqli_query($dbc, $q);
					}
				}
				
				
				if($r){
					
					$message = '<p class="alert alert-success">User was '.$action.'!</p>';
					
				} else {
					
					$message = '<p class="alert alert-danger">User could not be '.$action.' because: '.mysqli_error($dbc);
					if($verify == false) {
						$message .= '<p class="alert alert-danger">Password fields empty and/or do not match.</p>';
					}
					$message .= '<p class="alert alert-warning">Query: '.$q.'</p>';
					
				}
							
			}
			
			if(isset($_GET['id'])) { $opened = data_user($dbc, $_GET['id']); }
			
		break;
			
		case 'navigation':
		
			if(isset($_POST['submitted']) == 1) {
				
				$label = mysqli_real_escape_string($dbc, $_POST['label']);
				$url = mysqli_real_escape_string($dbc, $_POST['url']);
				
				if(isset($_POST['id']) != '') {
					
					$action = 'updated';
					$q = "UPDATE navigation SET id = '$_POST[id]', label = '$label', url = '$url', position = $_POST[position], status = $_POST[status] WHERE id = '$_POST[openedid]'";
					$r = mysqli_query($dbc, $q);
					
				} 
				
				if($r){
					
					$message = '<p class="alert alert-success">Navigation Item was '.$action.'!</p>';
					
				} else {
					
					$message = '<p class="alert alert-danger">Navigation Item could not be '.$action.' because: '.mysqli_error($dbc);
					$message .= '<p class="alert alert-warning">Query: '.$q.'</p>';
					
				}
							
			}
	
		
		break;
		
		case 'settings':
		
			if(isset($_POST['submitted']) == 1) {
				
				$label = mysqli_real_escape_string($dbc, $_POST['label']);
				$value = mysqli_real_escape_string($dbc, $_POST['value']);
				
				if(isset($_POST['id']) != '') {
					
					$action = 'updated';
					$q = "UPDATE settings SET id = '$_POST[id]', label = '$label', value = '$value' WHERE id = '$_POST[openedid]'";
					$r = mysqli_query($dbc, $q);
					
				} 
				
				
				if($r){
					
					$message = '<p class="alert alert-success">Setting was '.$action.'!</p>';
					
				} else {
					
					$message = '<p class="alert alert-danger">Setting could not be '.$action.' because: '.mysqli_error($dbc);
					$message .= '<p class="alert alert-warning">Query: '.$q.'</p>';
					
				}
							
			}
	
		
		break;		
		
		default:
			
		break;
	}
?>
```

<h1>Page Manager</h1>

<div class="row">
	
	<div class="col-md-3">
											
		<div class="list-group">
			
			<a class="list-group-item" href="?page=pages">
				<i class="fa fa-plus-circle"></i> New Page
			</a>				
		
		<?php
			
			$q = "SELECT * FROM pages ORDER by title ASC";
			$r = mysqli_query($dbc, $q);		
			
			while($list = mysqli_fetch_assoc($r)) { 
				
				$blurb = substr(strip_tags($list['body']), 0, 160);
				
		?>					
				
			<div id="page_<?php echo $list['id']; ?>"class="list-group-item <?php selected($list['id'], $opened['id'], 'active'); ?>">
				<h5 class="list-group-item-heading"><?php echo $list['title']; ?>
				<span class="pull-right">
					<a href="#" id="del_<?php echo $list['id']; ?>" class="btn btn-danger btn-sm btn-delete"><i class="far fa-trash-alt"></i></a>
					<a href="index.php?page=pages&id=<?php echo $list['id']; ?>" class="btn btn-primary btn-sm"><i class="far fa-edit"></i></a>
				</span>	
					
				</h5>								
				<p class="list-group-item-text"><?php echo $blurb; ?></p>	
			</div>	
			
				
		<?php } ?>
		
		</div>
		
	</div>
	
	<div class="col-md-9">
		
		<?php if(isset($message)) { echo $message; } ?>			
		
		<form action="index.php?page=pages&id=<?php echo $opened['id']; ?>" method="post" role="form">
			
			
			<div class="form-group">
				
				<label for="title">Title:</label>
				<input class="form-control" type="text" name="title" id="title" value="<?php echo $opened['title']; ?>" placeholder="Page Title">
				
			</div>							
			
			<div class="form-group">
				
				<label for="user">User:</label>
				<select class="form-control" name="user" id="user">
					
					<option value="0">No user</option>
					
					<?php
					
						$q = "SELECT id FROM users ORDER by first ASC";
						$r = mysqli_query($dbc, $q);
						
						while($user_list = mysqli_fetch_assoc($r)) { 
							
							$user_data = data_user($dbc, $user_list['id']);
							
						?>
							
							<option value="<?php echo $user_data['id']; ?>" 
								<?php 
								
									if(isset($_GET['id'])){
										selected($user_data['id'], $opened['user'], 'selected');												
									} else {
										selected($user_data['id'], $user['id'], 'selected');
									}
									
								?>><?php echo $user_data['fullname']; ?></option>
							
						<?php } ?>
					
					?>
					
				</select>
				
			</div>
			
			<div class="form-group">
				
				<label for="slug">Slug:</label>
				<input class="form-control" type="text" name="slug" id="slug" value="<?php echo $opened['slug']; ?>" placeholder="Page Slug">
				
			</div>
			
			<div class="form-group">
				
				<label for="label">Label:</label>
				<input class="form-control" type="text" name="label" id="label" value="<?php echo $opened['label']; ?>" placeholder="Page Label">
				
			</div>											
			
			<div class="form-group">
				
				<label for="header">Header:</label>
				<input class="form-control" type="text" name="header" id="header" value="<?php echo $opened['header']; ?>" placeholder="Page Header">
				
			</div>
			
			<div class="form-group">
				
				<label for="body">Body:</label>
				<textarea class="form-control editor" name="body" id="body" rows="8" placeholder="Page Body"><?php echo $opened['body']; ?></textarea>
				
			</div>
			
			<button type="submit" class="btn btn-outline-dark btn-sm">Save</button>
			<input type="hidden" name="submitted" value="1">
			<?php if(isset($opened['id'])){ ?>
			<input type="hidden" id="id" value="<?php echo $opened['id']; ?>">
			<?php } ?>	
			
			
		</form>				
		
	</div>
	
	
	
</div>

**Comment by creptor** [comment]
Hey @Th3-Gh057, I think the problem has something to do with the $opened['id'] variable. Please check what value it has (when editing a page), and before clicking update.

Please check the value of the input id.
(this line: `<input type="hidden" id="id" value="<?php echo $opened['id']; ?>">`)

**Comment by creptor** [comment]
Please use `var_dump($opened)` and send the response given by the server.

**Comment by Th3-Gh057** [comment]
Thank you @creptor for your instant answers to my issue. I tried to observe the value for $opened['id] variable but it gives me an headache.. I have no enough php knowledges, I am at the beginning, this is why I wanted to learn from thedigicraft which is awesome..  I executed var_dump($opened) and I received this: 

array(9) { ["id"]=> string(1) "1" ["user"]=> string(1) "1" ["slug"]=> string(4) "home" ["label"]=> string(4) "Home" ["title"]=> string(9) "Home Page" ["header"]=> string(21) "Welcome to DynaCoPlat" ["body"]=> string(3067)

Before I clicked update from the debug I received this: 

[opened] => Array
        (
            [id] => 1
            [user] => 1
            [slug] => home
            [label] => Home
            [title] => Home Page
            [header] => Welcome to DynaCoPlat
            [body] => 

After I clicked update debug shows these informations:

(
    [_GET] => Array
        (
            [page] => pages
            [id] => 1
        )

    [_POST] => Array
        (
            [title] => Home Page1
            [user] => 1
            [slug] => home
            [label] => Home
            [header] => Welcome to DynaCoPlat
            [body] =>

[submitted] => 1
        )
[action] => added
    [q] => SELECT id FROM users ORDER by first ASC
    [r] => mysqli_result Object
        (
            [current_field] => 0
            [field_count] => 1
            [lengths] => 
            [num_rows] => 7
            [type] => 0
        )

    [message] => 
Page was added!


    [opened] => Array
        (
            [id] => 1
            [user] => 1
            [slug] => home
            [label] => Home
            [title] => Home Page
            [header] => Welcome to DynaCoPlat
            [body] => 

If these results are not enough, you can please give me some directions how to check the values for $opened['id'] variable. Thank you so much for your support..

**Comment by Th3-Gh057** [comment]
Issue was resolved, the error was on line <input type="hidden" id="id" value="<?php echo $opened['id']; ?>"> where id="id" it was supposed to be name="id".
Thank you for your support.

**Comment by creptor** [comment]
Nice catch, sry for not being able to help in time. I have a lot stuff to do on the week 😅.

If you have any other problems, want some advice or information don't hesitate and post it here, I'll try to help you.
