### ISSUE TITLE
Sql Injection in /admin/login.php

### ISSUE THREAD

**Issue by jsjbcyber** [thedigicraft/Atom.CMS#255]
In /admin/login.php:

`<?php
.....
if($_POST) {
	$q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA1('$_POST[password]')";
	$r = mysqli_query($dbc, $q);
.....
?>`

When logging in at the background, you can log in at the background with the wrong password and account by the method of post.
post: /admin/login.php 
email=alan@alan.com'or '1'='1&password=123。
then, I can log in to the system with the wrong password

**Comment by creptor** [comment]
This project is just to get started and learn how to create web pages with php. I do not recommend an exact copy of this site to be used in production due to the many error the site has, like the one you have mentioned.

That said, to mitigate SQL injections you could replace the connection to the database and use PDO. It involves changes on many things but it should work for avoiding these injection issues with ease. [Link to manual](https://www.php.net/manual/en/book.pdo.php).

I'll try to post an example of some code I found, but give me some time.

**Comment by jsjbcyber** [comment]
OK

**Comment by jsjbcyber** [comment]
OK

**Comment by creptor** [comment]
I didn't find the exact place where it was very well explained, but you should be able to find multiple sources with more information on how to implement PDO.

To get you started you could look to this implementation that I used a while back... Maybe you could search with some of this code how to do certain stuff.

```
// database configuration
Config::write_db('db.system','mysql');
Config::write_db('db.host','127.0.0.1');
Config::write_db('db.port','3306');
Config::write_db('db.basename','xxxx');
Config::write_db('db.user','xxxx');
Config::write_db('db.password','xxxxx');
```

Class for creating and using the PDO connection:
```
// Core class, will be called for database connection and user data
class Core extends Config
{
    public $db,$user;
    private static $instance;

    private function __construct()
    {
        // building data source name from config
		$dsn = Config::read_db("db.system").":host=".Config::read_db("db.host").";dbname=".Config::read_db("db.basename").";port=".Config::read_db("db.port").";connect_timeout=15";
        // getting DB user from config                
        $user = Config::read_db("db.user");
        // getting DB password from config                
        $password = Config::read_db("db.password");

		//Check connection to database
		try{
        	$this->db = new PDO($dsn, $user, $password);
		}catch (PDOException $e){
        	echo $e->getMessage();
			die;
		}catch (Exception $e){
        	echo $e->getMessage();
			die;
    	}
    }

    public static function getInstance()
    {
		//Checks if the new class exists or creates it
        if (!isset(self::$instance))
        {
            $object = __CLASS__;
            self::$instance = new $object;
        }
        return self::$instance;
    }
}
```

Example of a function for a login implementation:
```
//user_handler
function login($email=null,$password=null){
	if($_POST['email']==null&&$_POST['password']==null){
		return(alert('warning','No se ingresaron todos los datos.',true));
	}

	$email=filter_var($_POST['email'],FILTER_SANITIZE_EMAIL);
	if(!filter_var($email,FILTER_VALIDATE_EMAIL)){
		$message=alert('warning','Correo invalido.');
	}else{
		$conn=Core::getInstance()->db->prepare('SELECT password,id FROM users WHERE email = ?');
		$conn->bindParam(1,$email,PDO::PARAM_STR);
		$conn->execute();
		if($conn->rowCount()==1){
			$data=$conn->fetch(PDO::FETCH_ASSOC);
			if(password_verify($password,$data['password'])){
				$_SESSION['user_id']=$data['id'];
				if(password_needs_rehash($data['password'],PASSWORD_DEFAULT)){
					$new_password=password_hash($password,PASSWORD_DEFAULT,array('cost'=>12));
					$conn=Core::getInstance()->db->prepare('UPDATE users SET password = ? WHERE id = ?');
					$conn->bindParam(1,$new_password,PDO::PARAM_STR);
					$conn->bindParam(2,$data['id'],PDO::PARAM_INT);
					$conn->execute();
					$conn=null;
				}
			}else{
				$message=alert('warning','Los datos son incorrectos.');
			}
		}else{
			$message=alert('warning','Los datos son incorrectos.');
		}
	}
	if(isset($message)){
		return $message;
	}
}
```

**Comment by jsjbcyber** [comment]
OK. I'll try it.

**Comment by creptor** [comment]
I just noted that the example provided was not complete.

I edited the comment [above](https://github.com/thedigicraft/Atom.CMS/issues/255#issuecomment-1024651222) to include the missing pieces of code.

**Comment by v-dumitrescu** [comment]
The branch "AtomCMS-2.1" contains security fixes.
