### ISSUE TITLE
Security problem in clean urls?

### ISSUE THREAD

**Issue by creptor** [thedigicraft/Atom.CMS#84]
I have used a sql injection test tool called sqlmap, and aparently (I just tried it today) it says there is a url sql injection posibility. And it's probably true due that there is no sanitazer from the slug get to the database connetion.

I would apreciate if you have a solution or if you know how to install iconv to follow this <a href="http://cubiq.org/the-perfect-php-clean-url-generator">thread</a>

I have search over for this with no current answer. Please help.

**Comment by BloodWolf89** [comment]
Ok than why are you complaining about it?

**Comment by creptor** [comment]
I guess I got anoyed because I had tor ead a lot sry.

**Comment by BloodWolf89** [comment]
No Problem. If the issues are solved, can you close this thread? :)

**Comment by loworm** [comment]
lol .. the guy just wanted the good

**Comment by loworm** [comment]
more infos are welcomed any time ;)

**Comment by creptor** [comment]
the explanation is on the code itself. And I also think I got a better way to do that but, I'm not going back, just read the cuotes in the code

**Comment by creptor** [comment]
I give here another way of doing this, where you don't need to change anything.
**I didn't post this first because you need a php version higher than 5.2.**

    function data_post($dbc, $id) {
	if(is_numeric($id)) {
		$stmt = $dbc->prepare('SELECT * FROM pages WHERE id = ?');
	} else {
		$stmt = $dbc->prepare('SELECT * FROM pages WHERE slug = ?');
	}
	$stmt->bind_param('s', $id);
	$stmt->execute();
	$res = $stmt->get_result();
	while ($data = $res->fetch_assoc()) {
		$data['body_nohtml'] = strip_tags($data['body']);
		if($data['body'] == $data['body_nohtml']) {
			$data['body_formatted'] = '<p>'.$data['body'].'</p>';
		} else {
			$data['body_formatted'] = $data['body'];	
		}
		return $data;
	}
    }
remember that this is inside the data.php or where you place the data_post function
