### ISSUE TITLE
Developing a Dynamic Website 2014 - Part 13

### ISSUE THREAD

**Issue by Bartinio** [thedigicraft/Atom.CMS#90]
Hello. I'm not good in English. But I have a question... I have a problem in part 13.. I wrote a code like in video, but have a syntax error. I'll try to show you my code..

http://snag.gy/WZghn.jpg this is the PrtScn

please help me someone!!! 

THKS!!!!

**Comment by Bartinio** [comment]
THKS Very much, I've sloved the issue...!!

**Comment by creptor** [comment]
good job. please if you found your issue close the issue.
