### ISSUE TITLE
Error: Page could not be added updated because: Table 'saudcms.page' doesn't exist  UPDATE page SET user = 1, slug='about-us', title='About Us', label='about', header='About Sauds Web', body='  hello world ..

### ISSUE THREAD

**Issue by Askd02** [thedigicraft/Atom.CMS#94]
cannot add or update page

**Comment by Askd02** [comment]
![man](https://cloud.githubusercontent.com/assets/10694732/5891401/0a3df3c0-a4b5-11e4-8091-eb07b157898f.png)

**Comment by Askd02** [comment]
this is my queries.php

![man](https://cloud.githubusercontent.com/assets/10694732/5891507/b4ce207a-a4bb-11e4-873a-933dd76d6814.png)

**Comment by creptor** [comment]
values is misspelled. It's supposed to be capital letter. (like this: VALUES)

**Comment by Askd02** [comment]
Thanks for the reply,I have corrected the values into capital VALUES but still im getting the same error

**Comment by Askd02** [comment]
now i have no errors but still i cant create or update a page

**Comment by creptor** [comment]
you got two diferent table there.... for the update is page, and for the insert is pages. look it up

**Comment by Askd02** [comment]
Thank you creptor its working now,but i dont understand why both of my pages are getting updated at once when i add a new page whereas i only want to change or add a new page. here is a pic
![man](https://cloud.githubusercontent.com/assets/10694732/5892581/4a2dd87a-a4e6-11e4-9e81-477e9c4aeed9.png)

**Comment by creptor** [comment]
ok.... I kind of not get what you just said but if you get 2 pages updated when you update 1 then it must be because of your id, so it doesn't make sense. if that is not what you said and it's something like new page = 2 pages tell me and please post your actual code with http://pastebin.com/

**Comment by Askd02** [comment]
I need two different pages like homepage and about us page . so wats wrong with my id  and how do i change it so i have two different pages?

**Comment by creptor** [comment]
O I see. in the update query you forgot the WHERE `id=$_GET[id]`

**Comment by creptor** [comment]
if it does work please close the issue

**Comment by Askd02** [comment]
Thanks
