### ISSUE TITLE
Developing a Dynamic Website 2014 - Part 28

### ISSUE THREAD

**Issue by maaka** [thedigicraft/Atom.CMS#95]
I know there are about 3 posts just like mine, but nothing recent.   I've gone as far as to copy login.php from repo, and I'm still unable to get directed to index.php after typing in credentials in login field.  I tried a few things to ensure at least my side was correct.  I added error checking after header location per another post, and no errors.  To ensure my connection.php config was correct, I changed password in the connections file and instantly got an error.  Changed it back, and all was well.  Like I said this is direct from repo, but posted below is my login.php script.  
<?php 

# Start Session:
session_start();

# Database Connection:
include('../config/connection.php');

if($_POST) {
	
	$q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA1('$_POST[password]')";
	$r = mysqli_query($dbc, $q);
	
	if(mysqli_num_rows($r) == 1) {
		
		$_SESSION['username'] = $_POST['email'];
		header('Location: index.php');
		
	}else {

          echo mysqli_error($dbc).'<br>'.$q; // show any mysql errors and echo out the query to look for other errors     

      }
	
	
}

?>

<!DOCTYPE html>
<html>
	
<head>

	<title>Admin Login</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?php include('config/css.php'); ?>
	
	<?php include('config/js.php'); ?>

</head>
	
<body>
	
	<div id="wrap">		
			
		<?php //include(D_TEMPLATE.'/navigation.php'); // Main Navigation ?>

		<div class="container">

			<div class="row">

				<div class="col-md-4 col-md-offset-4">
				
					<div class="panel panel-info">
					
						<div class="panel-heading">
							<strong>Login</strong>
						</div>
						
						<div class="panel-body">
						
							<form action="login.php" method="post" role="form">
								
							  <div class="form-group">
							    <label for="email">Email address</label>
							    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
							  </div>
							  
							  <div class="form-group">
							    <label for="password">Password</label>
							    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
							  </div>
							  
							  
							  
							  <button type="submit" class="btn btn-default">Submit</button>
							  
							</form>
						
						</div>
					
					</div>				
					
				</div>
				
								
			</div>
			
		
			
		</div>

	</div>		

	<?php //include(D_TEMPLATE.'/footer.php'); // Page Footer ?>		

	<?php //if($debug == 1) { include('widgets/debug.php'); } ?>
	
</body>

</html>

**Comment by maaka** [comment]
Figured it out, it was a noob mistake.  In index.php i didn't capitalize "$_SESSION".  Hopefully this helps someone else

**Comment by creptor** [comment]
it's good that you have figuered it out. please now close the issue
